<div class="pagination pagination-centered">
  <ul>
    {if $paginator->isFirst()}
      <li class="disabled"><span>&laquo;</span></li>
  	{else}
  	  <li><a href="{link page, $paginator->page - 1}">&laquo;</a></li>
  	{/if}

  	{foreach $steps as $step}
    	{if isset($prevStep) && $step - $prevStep > 1}<li class="disabled"><span>...</span></li>{/if}
    	{if $step == $paginator->page}
    		<li class="disabled"><span class="current">{$step}</span></li>
    	{else}
    		<li><a href="{link page, $step}">{$step}</a></li>
    	{/if}
    	{? $prevStep = $step }
  	{/foreach}

  	{if $paginator->isLast()}
      <li class="disabled"><span>&raquo;</span></li>
  	{else}
  	  <li><a href="{link page, $paginator->page + 1}">&raquo;</a></li>
  	{/if}
  </ul>
</div>
