<!DOCTYPE html>
<html lang="cs">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{$pageTitle}</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
  <link rel="stylesheet" href="{$baseUri}css/styles.css" type="text/css" />
  <link rel="stylesheet" media="print" href="{$baseUri}css/print.css" type="text/css" />

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
</head>

<body>

<!--
<div class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="{plink Default:}"  title="Úvodní strana „Region Beskydy“ volejbalové ligy">„Region Beskydy“ volejbalová liga</a>
    </div>
  </div>
</div>
-->

<div id="header" class="container">
  <div class="row">
    <div class="col-md-12">
      <a href="{plink Default:}"  title="Úvodní strana „Region Beskydy“ volejbalové ligy"><h1>„Region Beskydy“ volejbalová liga</h1></a>
      <h2>Pojďme se bavit volejbalem v každém věku</h2>
    </div>
  </div>
</div>

<div class="container-fluid darkgreen">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <nav role="navigation" class="navbar navbar-default">
          <div class="navbar-header">
            <button data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" class="navbar-toggle" type="button"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
          </div>

        </nav>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div id="header"></div>

  <div class="row">
    <div id="sidebar" class="col-md-3">
      {include menu.phtml}

    	{if isset($user)}
    	<p id="logged-in">Uživatel: <strong>{$user->username}</strong></p>
      <ul>
        <li><a href="{link Uzivatele:}" title="Správa uživatelů">Uživatelé</a></li>
        <li><a href="{link Uzivatele:change}" title="Změna uživatelského jména a hesla">Změna hesla</a></li>
        <li><a href="{link Auth:logout}" title="Odhlášení z administrace">Odhlášení</a></li>
      </ul>
    	{/if}

    </div> <!-- #sidebar -->
    <div id="main" class="col-md-9">
      {if $pageHeading}
      <h1>{!$pageHeading}</h1>
      {/if}

      {foreach $flashes as $flash}
      <p class="alert alert-{$flash->type}">{$flash->message}</p>
      {/foreach}

      {include $content}
    </div> <!-- #main -->
  </div> <!-- .row -->
</div> <!-- .container -->

<div id="footer" class="text-center">
  <a href="http://www.regionbeskydy.cz/" title="Region Beskydy"><img src="{$baseUri}img/logos/rb_logo.jpg" width="80px" height="100px" alt="Region Beskydy" /></a>

  <p>
    <a href="{link Auth:login}" title="">administrace</a><br />
  </p>
</div><!-- #footer -->


{if isset($scripts)}
  {if in_array('datepicker', $scripts)}
  <link rel="stylesheet" href="{$baseUri}css/datepicker.css" type="text/css" />
  <script type="text/javascript" src="{$baseUri}js/bootstrap-datepicker.js"></script>
  <script type="text/javascript" src="{$baseUri}js/bootstrap-datepicker.cs.js"></script>
  <script type="text/javascript">
  $(document).ready(function(){
    $('.datepicker').datepicker( { autoclose: true, language: 'cs' } );
    $('.datepicker').addClass('form-control');
  });
  </script>
  {/if}
  {if in_array('antispam', $scripts)}
  <script type="text/javascript" src="{$baseUri}js/antispam.js"></script>
  {/if}
  {if in_array('lightbox', $scripts)}
  <link rel="stylesheet" href="{$baseUri}css/lightbox.css" type="text/css" media="screen" />
  <script type="text/javascript" src="{$baseUri}js/lightbox.min.js"></script>
  {/if}
  {if in_array('autocomplete', $scripts)}
    <link rel="stylesheet" href="{$baseUri}css/autocomplete-jquery-ui.min.css" type="text/css" media="screen" />
    <script type="text/javascript" src="{$baseUri}js/autocomplete-jquery-ui.min.js"></script>
  {/if}
  {if in_array('vysledky', $scripts)}
    <script type="text/javascript" src="{$baseUri}js/vysledky.js"></script>
  {/if}
{/if}



<!-- google analytics START -->
<script>
//   (function(i,s,o,g,r,a,m) { i['GoogleAnalyticsObject']=r;i[r]=i[r]||function() {
//   (i[r].q=i[r].q||[]).push(arguments) } ,i[r].l=1*new Date();a=s.createElement(o),
//   m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
//   } )(window,document,'script','//www.google-analytics.com/analytics.js','ga');
//   ga('create', 'UA-1224661-6', 'auto');
//   ga('send', 'pageview');
</script>
</body>
</html>
