<!DOCTYPE html>
<html lang="cs">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{$pageTitle}</title>
<!-- kvuli IE8 a respond.js nemohou byt css linkovana crossdomain, ale pouze lokalne */
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
-->
  <link rel="stylesheet" href="{$baseUri}css/bootstrap.min.css">
  <link rel="stylesheet" href="{$baseUri}css/bootstrap-theme.min.css">
  <link rel="stylesheet" href="{$baseUri}css/styles.css" type="text/css" />
  <link rel="stylesheet" media="print" href="{$baseUri}css/print.css" type="text/css" />

  <!-- kvuli IE8 se nemuze pouzit jquery 2, ale pouze 1.x -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="{$baseUri}js/bootstrap.min.js"></script>

  <link rel="stylesheet" href="{$baseUri}css/lightbox.css" type="text/css" media="screen" />
  <script type="text/javascript" src="{$baseUri}js/lightbox.min.js"></script>

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  <link rel="shortcut icon" href="{$baseUri}favicon.ico">
</head>

<body {ifCurrent Default:*}class="homepage"{/if}>

<div id="header" class="navbar navbar-default">

  <div class="container">
    <div class="row">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
{*
        <a href="{plink Default:}" class="navbar-brand" title="Úvodní stránka">
          <h1>„Region Beskydy“ volejbalová liga</h1>
          <p class="hidden-xs">Pojďme se bavit volejbalem v každém věku</p>
        </a>
*}
      </div> <!-- .navbar-header -->
    </div> <!-- .row -->
  </div> <!-- .container -->

  <div id="menu">
    <div class="container">
      <div class="row">
        <div class="collapse navbar-collapse" id="menu-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{plink Default:}" title="Informace o „Region Beskydy“ volejbalové lize">Úvod</a></li>
            <li><a href="{plink Aktuality:}" title="Aktuality z „Region Beskydy“ volejbalové ligy">Novinky</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Aktuální ročník <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{plink Propozice:}" title="Propozice pro přihlášení družstva">Propozice</a></li>
                <li><a href="{plink Pravidla:}" title="Pravidla soutěže">Pravidla</a></li>
<!--
                <li><a href="{plink Vysledky:}" title="Výsledky aktuálního ročníku">Výsledky</a></li>
                <li><a href="{plink Rozlosovani:}" title="Rozlosování aktuálního ročníku">Rozlosování</a></li>
                <li><a href="{plink Druzstva:}" title="Družstva hrající „Region Beskydy“ volejbalovou ligu">Družstva</a></li>
                {if isset($user)}
                <li><a href="{plink Hraci:}" title="Evidence hráčů">Hráči</a></li>
                {/if}
-->
              </ul>
            </li>
            <li><a href="{plink Download:}" title="Dokumenty ke stažení">Ke stažení</a></li>
            <li><a href="{plink Kontakty:}" title="Kontakty na vedení „Region Beskydy“ volejbalové ligy">Kontakty</a></li>
            <li><a href="{plink Dary:}" title="Dotace a dary pro „Region Beskydy“ volejbalovou ligu">Dotace a dary</a></li>
            <li><a href="{plink Diskuze:}" title="Diskuze návštěvníků">Diskuze</a></li>
            <li><a href="{plink Akce:}" title="Volejbalové turnaje a akce v Regionu Beskydy">Turnaje</a></li>
          </ul>
        </div> <!-- navbar-collapse -->
      </div> <!-- .row -->
    </div> <!-- .container -->
  </div> <!-- #menu -->
</div> <!-- .navbar -->

<div class="section-title">
  <div class="overlay-bg"></div>
  <div class="container">
    <h1>{!$pageHeading}</h1>
  </div>
</div>

<div class="content-info">

  <div class="crumbs  hidden-xs">
  </div>

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        {foreach $flashes as $flash}
        <p class="alert alert-{$flash->type}">{$flash->message}</p>
        {/foreach}
        {include $content}
      </div>
    </div> <!-- .row -->
  </div> <!-- .container -->

  <div class="section-wide bottom">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <h4>Pořadatel</h4>
          <p>Beskydská volejbalová liga amatérů<br>V. Nezvala 549, Frýdek-Místek<br>IČ 02694409</p>
          {if isset($user)}
            {$user->username}
            <a href="{link Auth:logout}" class="btn btn-primary" title="Odhlášení uživatele"><span class="glyphicon glyphicon-off"></span></a>
          <ul>
            <li><a href="{link Uzivatele:change}" title="Změna uživatelského jména a hesla">Změna hesla</a></li>
          </ul>
          {else}
            <a href="{link Auth:login}" class="btn btn-primary" title="Přihlášení uživatele"><span class="glyphicon glyphicon-user"></span></a>
          {/if}
        </div>
        <div class="col-md-4">
          <div class="text-center">
            <a href="http://www.frydekmistek.cz/" title="Frýdek-Místek"><img src="{$baseUri}img/fm-logo2.png" height="100px" width="77px" alt="Frýdek-Místek" /></a>
            <a href="http://www.regionbeskydy.cz/" title="Region Beskydy"><img src="{$baseUri}img/rb-logo.png" height="100px" width="77px" alt="Region Beskydy" /></a>
          </div>
        </div>
        <div class="col-md-4">
        </div>
      </div> <!-- .row -->
    </div> <!-- .container -->
  </div> <!-- .section-wide -->
</div> <!-- .content-info -->

{*
<div id="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <h4>Pořadatel</h4>
        <p>Beskydská volejbalová liga amatérů<br>V. Nezvala 549, Frýdek-Místek<br>IČ 02694409</p>
        {if isset($user)}
          {$user->username}
          <a href="{link Auth:logout}" class="btn btn-primary" title="Odhlášení uživatele"><span class="glyphicon glyphicon-off"></span></a>
        <ul>
          <li><a href="{link Uzivatele:change}" title="Změna uživatelského jména a hesla">Změna hesla</a></li>
        </ul>
        {else}
          <a href="{link Auth:login}" class="btn btn-primary" title="Přihlášení uživatele"><span class="glyphicon glyphicon-user"></span></a>
        {/if}
      </div>
      <div class="col-md-6">
        <h4 class="">Vítězové minulého ročníku</h4>
        <ul class="thumbs">
          <li>
            <a href="{$baseUri}img/vitezove/1415-1-skokani.jpg" rel="lightbox['vitezove']" title="Skokani - mistr ligy 2014-2015">
              <img src="{$baseUri}img/vitezove/thumb_1415-1-skokani.jpg" />
            </a>
            <p>Skokani<br>mistr ligy 2014-2015</p>
          </li>
          <li>
            <a href="{$baseUri}img/vitezove/1415-2-wadovice.jpg" rel="lightbox['vitezove']" title="Wadovice - druhé místo">
              <img src="{$baseUri}img/vitezove/thumb_1415-2-wadovice.jpg" />
            </a>
            <p>Wadowice<br>druhé místo</p>
          </li>
          <li>
            <a href="{$baseUri}img/vitezove/1415-3-raskovice.jpg" rel="lightbox['vitezove']" title="Raškovice - třetí místo">
              <img src="{$baseUri}img/vitezove/thumb_1415-3-raskovice.jpg" />
            </a>
            <p>Raškovice<br>třetí místo</p>
          </li>
        </ul>
      </div>
      <div class="col-md-3 text-right">
      </div>
    </div> <!-- .row -->
  </div> <!-- .container -->
</div> <!-- #footer -->
*}

<div class="footer-down">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <ul class="nav-footer">
            <li><a href="{plink Default:}" title="Informace o „Region Beskydy“ volejbalové lize">ÚVOD</a> </li>
            <li><a href="{plink Aktuality:}" title="Aktuality z „Region Beskydy“ volejbalové ligy">NOVINKY</a></li>
            <li><a href="{plink Vysledky:}" title="Výsledky aktuálního ročníku">VÝSLEDKY</a></li>
            <li><a href="{plink Download:}" title="Dokumenty ke stažení">KE STAŽENÍ</a></li>
            <li><a href="{plink Kontakty:}" title="Kontakty na vedení „Region Beskydy“ volejbalové ligy">KONTAKTY</a></li>
        </ul>
      </div>
    </div> <!-- .row -->
  </div> <!-- .container -->
</div> <!-- .footer-down -->


{if isset($scripts)}
  {if in_array('datepicker', $scripts)}
  <link rel="stylesheet" href="{$baseUri}css/datepicker.css" type="text/css" />
  <script type="text/javascript" src="{$baseUri}js/bootstrap-datepicker.js"></script>
  <script type="text/javascript" src="{$baseUri}js/bootstrap-datepicker.cs.js"></script>
  <script type="text/javascript">
  $(document).ready(function(){
    $('.datepicker').datepicker( { autoclose: true, language: 'cs' } );
    $('.datepicker').addClass('form-control');
  });
  </script>
  {/if}
  {if in_array('antispam', $scripts)}
  <script type="text/javascript" src="{$baseUri}js/antispam.js"></script>
  {/if}
  {if in_array('lightbox', $scripts)}
  {/if}
  {if in_array('autocomplete', $scripts)}
    <link rel="stylesheet" href="{$baseUri}css/autocomplete-jquery-ui.min.css" type="text/css" media="screen" />
    <script type="text/javascript" src="{$baseUri}js/autocomplete-jquery-ui.min.js"></script>
  {/if}
  {if in_array('vysledky', $scripts)}
    <script type="text/javascript" src="{$baseUri}js/vysledky.js"></script>
  {/if}
{/if}



<!-- google analytics START -->
<script>
//   (function(i,s,o,g,r,a,m) { i['GoogleAnalyticsObject']=r;i[r]=i[r]||function() {
//   (i[r].q=i[r].q||[]).push(arguments) } ,i[r].l=1*new Date();a=s.createElement(o),
//   m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
//   } )(window,document,'script','//www.google-analytics.com/analytics.js','ga');
//   ga('create', 'UA-1224661-6', 'auto');
//   ga('send', 'pageview');
</script>
</body>
</html>
