<!DOCTYPE html>
<html lang="cs">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{$pageTitle}</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
  <link rel="stylesheet" href="{$baseUri}css/styles.css" type="text/css" />
  <link rel="stylesheet" media="print" href="{$baseUri}css/print.css" type="text/css" />

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

  <link rel="stylesheet" href="{$baseUri}css/lightbox.css" type="text/css" media="screen" />
  <script type="text/javascript" src="{$baseUri}js/lightbox.min.js"></script>

  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,600,700&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
</head>

<body {ifCurrent Default:*}class="homepage"{/if}>

<div id="header">
  <div class="container">
    <div class="row">
      <div class="col-md-10">
        <a href="{plink Default:}" class="brand" title="Úvodní stránka">
          <h1>„Region Beskydy“ volejbalová liga</h1>
          <p>Pojďme se bavit volejbalem v každém věku</p>
        </a>
      </div>
      <div class="col-md-2">
        {if isset($user)}
        <p id="logged-in">Uživatel: <strong>{$user->username}</strong></p>
        <ul>
          <li><a href="{link Uzivatele:}" title="Správa uživatelů">Uživatelé</a></li>
          <li><a href="{link Uzivatele:change}" title="Změna uživatelského jména a hesla">Změna hesla</a></li>
          <li><a href="{link Auth:logout}" title="Odhlášení z administrace">Odhlášení</a></li>
        </ul>
        {/if}
      </div>
    </div>
  </div>
</div>

<div id="menu" class="navbar navbar-default">
  <div class="container">
    <div class="row">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#menu-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <div class="navbar-collapse" id="menu-collapse">
        <ul class="nav navbar-nav">
          <li><a href="{plink Default:}" title="Informace o „Region Beskydy“ volejbalové lize">Úvod</a></li>
          <li><a href="{plink Aktuality:}" title="Aktuality z „Region Beskydy“ volejbalové ligy">Novinky</a></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Aktuální ročník <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{plink Vysledky:}" title="Výsledky aktuálního ročníku">Výsledky</a></li>
              <li><a href="{plink Rozlosovani:}" title="Rozlosování aktuálního ročníku">Rozlosování</a></li>
              <li><a href="{plink Propozice:}" title="Propozice pro přihlášení družstva">Propozice</a></li>
              <li><a href="{plink Pravidla:}" title="Pravidla soutěže">Pravidla</a></li>
              <li><a href="{plink Foto:}" title="Fotografie z průběhu „Region Beskydy“ volejbalové ligy">Fotogalerie</a></li>
            </ul>
          </li>
          <li><a href="{plink Download:}" title="Dokumenty ke stažení">Ke stažení</a></li>
          <li><a href="{plink Kontakty:}" title="Kontakty na vedení „Region Beskydy“ volejbalové ligy">Kontakty</a></li>
          <li><a href="{plink Diskuze:}" title="Diskuze návštěvníků">Diskuze</a></li>
          <li><a href="{plink Akce:}" title="Volejbalové turnaje a akce v Regionu Beskydy">Turnaje</a></li>
        </ul>
      </div>
    </div> <!-- .row -->
  </div> <!-- .container -->
</div> <!-- .navbar -->

<section class="section-title">
  <div class="overlay-bg"></div>
  <div class="container">
    <h1>{!$pageHeading}</h1>
  </div>
</section>

<div class="content-info">

  <div class="crumbs">
<!--
      <ul>
        <li><a href="index.html">Home</a></li>
        <li>/</li>
        <li>About Us</li>
      </ul>
-->
  </div>

  <div class="container">
    <div class="row">
      <div class="col-md-12">
        {foreach $flashes as $flash}
        <p class="alert alert-{$flash->type}">{$flash->message}</p>
        {/foreach}
        {include $content}
      </div>
    </div> <!-- .row -->
  </div> <!-- .container -->

  <div class="section-wide">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="text-center">
            <a href="http://www.regionbeskydy.cz/" title="Region Beskydy"><img src="{$baseUri}img/rb_logo.png" height="100px" width="77px" alt="Region Beskydy" /></a>
          </div>
<span class="pull-right">
  <a href="{link Auth:login}" title="">administrace</a><br />
</span>
        </div>
      </div> <!-- .row -->
    </div> <!-- .container -->
  </div> <!-- .section-wide -->
</div> <!-- .content-info -->


<div id="footer">
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h4 class="text-center">Vítězové minulého ročníku</h4>
        <ul class="thumbs">
          <li>
            <a href="{$baseUri}img/vitezove/1415-1-skokani.jpg" rel="lightbox['vitezove']" title="Skokani - mistr ligy 2014-2015">
              <img src="{$baseUri}img/vitezove/thumb_1415-1-skokani.jpg" />
            </a>
            <p>Skokani<br>mistr ligy 2014-2015</p>
          </li>
          <li>
            <a href="{$baseUri}img/vitezove/1415-2-wadovice.jpg" rel="lightbox['vitezove']" title="Wadovice - druhé místo">
              <img src="{$baseUri}img/vitezove/thumb_1415-2-wadovice.jpg" />
            </a>
            <p>Wadowice<br>druhé místo</p>
          </li>
          <li>
            <a href="{$baseUri}img/vitezove/1415-3-raskovice.jpg" rel="lightbox['vitezove']" title="Raškovice - třetí místo">
              <img src="{$baseUri}img/vitezove/thumb_1415-3-raskovice.jpg" />
            </a>
            <p>Raškovice<br>třetí místo</p>
          </li>
        </ul>
      </div>
    </div> <!-- .row -->
  </div> <!-- .container -->
</div> <!-- #footer -->

<div class="footer-down">
  <div class="container">
    <div class="row">
      <div class="col-md-5">
          <p>&copy; 2015 Beskydská volejbalová liga amatérů</p>
      </div>
      <div class="col-md-7">
        <ul class="nav-footer">
            <li><a href="{plink Default:}" title="Informace o „Region Beskydy“ volejbalové lize">ÚVOD</a> </li>
            <li><a href="{plink Aktuality:}" title="Aktuality z „Region Beskydy“ volejbalové ligy">NOVINKY</a></li>
            <li><a href="{plink Vysledky:}" title="Výsledky aktuálního ročníku">VÝSLEDKY</a></li>
            <li><a href="{plink Download:}" title="Dokumenty ke stažení">KE STAŽENÍ</a></li>
            <li><a href="{plink Kontakty:}" title="Kontakty na vedení „Region Beskydy“ volejbalové ligy">KONTAKTY</a></li>
        </ul>
      </div>
    </div> <!-- .row -->
  </div> <!-- .container -->
</div> <!-- .footer-down -->


{if isset($scripts)}
  {if in_array('datepicker', $scripts)}
  <link rel="stylesheet" href="{$baseUri}css/datepicker.css" type="text/css" />
  <script type="text/javascript" src="{$baseUri}js/bootstrap-datepicker.js"></script>
  <script type="text/javascript" src="{$baseUri}js/bootstrap-datepicker.cs.js"></script>
  <script type="text/javascript">
  $(document).ready(function(){
    $('.datepicker').datepicker( { autoclose: true, language: 'cs' } );
    $('.datepicker').addClass('form-control');
  });
  </script>
  {/if}
  {if in_array('antispam', $scripts)}
  <script type="text/javascript" src="{$baseUri}js/antispam.js"></script>
  {/if}
  {if in_array('lightbox', $scripts)}
  {/if}
  {if in_array('autocomplete', $scripts)}
    <link rel="stylesheet" href="{$baseUri}css/autocomplete-jquery-ui.min.css" type="text/css" media="screen" />
    <script type="text/javascript" src="{$baseUri}js/autocomplete-jquery-ui.min.js"></script>
  {/if}
  {if in_array('vysledky', $scripts)}
    <script type="text/javascript" src="{$baseUri}js/vysledky.js"></script>
  {/if}
{/if}



<!-- google analytics START -->
<script>
//   (function(i,s,o,g,r,a,m) { i['GoogleAnalyticsObject']=r;i[r]=i[r]||function() {
//   (i[r].q=i[r].q||[]).push(arguments) } ,i[r].l=1*new Date();a=s.createElement(o),
//   m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
//   } )(window,document,'script','//www.google-analytics.com/analytics.js','ga');
//   ga('create', 'UA-1224661-6', 'auto');
//   ga('send', 'pageview');
</script>
</body>
</html>
