{!$form}

<h2>Nápověda</h2>

<p>
  <a href="http://texy.info/cs/syntax">http://texy.info/cs/syntax</a>
</p>

<h3>Odstavce</h3>
<p>
  Jednotlivé odstavce musí být odděleny prázdným řádkem:
</p>

<p>
První odstavec lorem ipsum dolor sit amet.
<br><br>
Druhý odstavec, dfhdsjnk nůdsfklm sdafma-m as,d.fmdas amsdfjk .asdhf.
</p>


<h3>Fráze</h3>
<p>
  //kurzíva//    - vypíše text <em>kurzívou</em>
</p>
<p>
  **tučné**     -   vypíše text <strong>tučně</strong>
</p>

<h3>Seznamy</h3>
<p>
  Odrážkové seznamy zapisujeme pomocí <strong>* +</strong> nebo <strong>-</strong>. Musí být zapsán hned na začátku řádku a za ním musí následovat mezera.
</p>
<p>
  - první položka<br />
  - druhá položka<br />
  - třetí položka
</p>

<h3>Číslované seznamy</h3>
<p>
  Existují tyto čtyři varianty zápisu:
</p>
<p>
1)  Učit se<br />
2)  Učit se<br />
3)  Učit se<br />
<br />
a)  Dlouhý<br />
b)  Široký<br />
c)  Krátkozraký<br />
<br />
A)  první<br />
B)  druhý<br />
C)  třetí<br />
<br />
I)  Yesterday<br />
II)  Today<br />
III)  Tomorrow<br />  
</p>