<div class="panel-box">
  <div class="row">
    <div class="col-md-12">
{if isset($user)}
<p class="text-center">
  <a class="btn btn-primary btn-lg" href="{link add}" title="Přidat novou aktualitu"><span class="glyphicon glyphicon-plus"></span> Přidat aktualitu</a>
</p>
{/if}


{if !count($rows)}
  <p>
    Nejsou uloženy žádné příspěvky
  </p>
{else}

  {?$dataGrid->renderPaginator()}

  {foreach $rows as $row}
  <div class="post-item">
    <div class="row">
      <div class="col-md-12">
        <h4>
          {$row->vlozeno|date:'%d.%m.%Y'}
          {if isset($user)}
            <div class="btn-group pull-right">
              <a class="btn btn-default" href="{link edit, $row->id}" title="upravit příspěvek"><span class="glyphicon glyphicon-pencil"></span></a>
              <a class="btn btn-default" href="{link delete, $row->id}" title="smazat příspěvek"><span class="glyphicon glyphicon-remove"></span></a>
            </div>
          {/if}
        </h4>
        {!$row->text |texy}
      </div>
    </div>
  </div>
  {/foreach}

  {?$dataGrid->renderPaginator()}

{/if}
    </div>
  </div>
</div>
