{if isset($user)}
<p>
  <a class="btn btn-success" href="{link add}" title="Přidat novou aktualitu"><span class="glyphicon glyphicon-plus"></span> Nová aktualita</a>
</p>
{/if}

{if !count($rows)}
  <p>
    Nejsou uloženy žádné příspěvky
  </p>
{else}

  {?$dataGrid->renderPaginator()}

  {foreach $rows as $row}
    {if isset($user)}
      <div class="btn-group pull-right">
        <a class="btn btn-default" href="{link edit, $row->id}" title="upravit příspěvek"><span class="glyphicon glyphicon-pencil"></span></a>
        <a class="btn btn-default" href="{link delete, $row->id}" title="smazat příspěvek"><span class="glyphicon glyphicon-remove"></span></a>
      </div>
    {/if}
    <h4 class="clearfix">{$row->vlozeno|date:'%d.%m.%Y'}</h4>
    {!$row->text |texy}

    {if !$iterator->last}
      <hr>
    {/if}
  {/foreach}

  {?$dataGrid->renderPaginator()}

{/if}


