<div class="row">
  <div class="col-md-6">
    <div class="panel-box">
      <div class="row">
        <div class="col-md-12">
          {if isset($user)}
          <p>
            <a class="btn btn-default pull-right" href="{link Stranky:edit, 1}" title="Upravit text úvodní stránky"><span class="glyphicon glyphicon-pencil"></span> Upravit text</a>
          </p>
          {/if}
          {!$text|texy}
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-3">
    <div class="panel-box">
      <div class="titles">
        <h4>Výsledky aktuálního kola</h4>
      </div>
      <ul>
        <li>Liga A - základní část<br><a href="#">Hrací den č. 5</a> - 15.2.2015</li>
        <li>Liga B - finále<br><a href="#">Hrací den č. 5</a> - 15.2.2015</li>
      </ul>
    </div>
    <div class="panel-box">
      <div class="titles">
        <h4>Liga A - tabulka</h4>
      </div>
      <table class="table table-hover table-condensed">
        <thead>
          <tr><th>pořadí</th><th>družstvo</th><th>body</th></tr>
        </thead>
        <tbody>
          <tr><td>1.</td><td>Wadowice</td><td>35</td></tr>
          <tr><td>2.</td><td>VETERÁNI a spol.</td><td>34</td></tr>
          <tr><td>3.</td><td>VK OB-NOVA</td><td>30</td></tr>
          <tr><td>4.</td><td>Raškovice</td><td>28</td></tr>
          <tr><td>5.</td><td>ANTIFÉRTÝM</td><td>26</td></tr>
          <tr><td>6.</td><td>Nováčci</td><td>26</td></tr>
          <tr><td>7.</td><td>Skokani</td><td>25</td></tr>
          <tr><td>8.</td><td>BVC ČADCA</td><td>25</td></tr>
          <tr><td>9.</td><td>Rintintin</td><td>24</td></tr>
          <tr><td>10.</td><td>RADEGAST</td><td>24</td></tr>
          <tr><td>11.</td><td>HUKVALDY</td><td>19</td></tr>
          <tr><td>12.</td><td>Šenow</td><td>19</td></tr>
          <tr><td>13.</td><td>S.T.O.H.</td><td>15</td></tr>
          <tr><td>14.</td><td>Sokol Vsetín</td><td>14</td></tr>
          <tr><td>15.</td><td>TJ Sokol Frenštát p. R.</td><td>11</td></tr>
          <tr><td>16.</td><td>STS CHVOJKOVICE BROD</td><td>5</td></tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="col-md-3">
    <div class="panel-box">
      <div class="titles">
        <h4>Rozlosování příštího kola</h4>
      </div>
      <ul>
        <li>Liga A - základní část<br><a href="#">Hrací den č. 5</a> - 15.2.2015</li>
        <li>Liga B - finále<br><a href="#">Hrací den č. 5</a> - 15.2.2015</li>
      </ul>
    </div>

    <div class="panel-box">
      <div class="titles">
        <h4>Liga B - tabulka</h4>
      </div>
      <p><strong>Liga B - finálová skupina B3</strong></p>
      <table class="table table-hover table-condensed">
        <thead>
          <tr><th>pořadí</th><th>družstvo</th><th>body</th></tr>
        </thead>
        <tbody>
          <tr><td>1.</td><td>SAN PIETRO</td><td>25</td></tr>
          <tr><td>2.</td><td>BOSS MOSTY</td><td>22</td></tr>
          <tr><td>3.</td><td>ČSAD F-M</td><td>15</td></tr>
          <tr><td>4.</td><td>Pupíci</td><td>15</td></tr>
          <tr><td>5.</td><td>Calvados</td><td>13</td></tr>
          <tr><td>6.</td><td>Plum Stars</td><td>12</td></tr>
          <tr><td>7.</td><td>Q-team</td><td>9</td></tr>
          <tr><td>8.</td><td>TUX team</td><td>9</td></tr>
          <tr><td>9.</td><td>DAN TEAM</td><td>8</td></tr>
          <tr><td>10.</td><td>MAMMA MIA</td><td>7</td></tr>
      </tbody></table>

      <p><strong>Liga B - finálová skupina B4</strong></p>
      <table class="table table-hover table-condensed">
        <thead>
          <tr><th>pořadí</th><th>družstvo</th><th>body</th></tr>
        </thead>
        <tbody>
          <tr><td>1.</td><td>Ostravička</td><td>19</td></tr>
          <tr><td>2.</td><td>Osmička</td><td>17</td></tr>
          <tr><td>3.</td><td>POHODA</td><td>16</td></tr>
          <tr><td>4.</td><td>Kalamita</td><td>15</td></tr>
          <tr><td>5.</td><td>Sinusoida 2010</td><td>15</td></tr>
          <tr><td>6.</td><td>Dapsáci</td><td>14</td></tr>
          <tr><td>7.</td><td>Tornádo Pržno</td><td>13</td></tr>
          <tr><td>8.</td><td>Řepiště</td><td>11</td></tr>
          <tr><td>9.</td><td>ŠESTKY</td><td>9</td></tr>
          <tr><td>10.</td><td>Volejbalíci</td><td>6</td></tr>
        </tbody>
      </table>
    </div>
  </div>
</div> <!-- .row -->

<!--
<p class="alert alert-warning">
  už nyní se můžete přihlašovat do nového ročníku „RB“VL. <strong>Uzávěrka přihlášek je 15.9.2014!</strong>
</p>

<p>
 Veškeré informace získáte na těchto webových stránkách v&nbsp;sekcích <a href="{plink Pravidla:}">Pravidla</a>
 a&nbsp;<a href="{plink Propozice:}">Propozice</a>. Přihlášku a&nbsp;soupisku najdete v&nbsp;sekci <a href="{plink Download:}">Ke stažení</a>.
</p>
-->
