<p>
 Vážení volejbaloví přátelé,
</p>
<p>
 Správní rada spolu s&nbsp;f. SPORT SERVIS Frýdlant n. O. vyhlašují jubilejní
 5.ročník&nbsp;„REGION BESKYDY“ amatérské volejbalové ligy smíšených družstev
 2013-2014.
</p>
<p>
 Srdečně zveme všechna družstva, která již soutěž v&nbsp;minulých ročnících
 absolvovala, ale také nová družstva, která mají chuť si od října 2013 do
 března 2014 zahrát volejbal.
</p>
<p>
 Veškeré informace získáte na těchto webových stránkách v&nbsp;sekcích <a href="{plink Pravidla:}">Pravidla</a>
 a&nbsp;<a href="{plink Propozice:}">Propozice</a>. Přihlášku a&nbsp;soupisku najdete v&nbsp;sekci <a href="{plink Download:}">Ke stažení</a>.
</p>
<p>
 Prosíme všechny zájemce, aby s&nbsp;přihláškou do 5. ročníku příliš neotáleli
 a&nbsp;dodrželi termín 13. září 2013. Vaše účast se stává potvrzenou v&nbsp;okamžiku
 dodání přihlášky a&nbsp;soupisky a&nbsp;uhrazení startovného.
</p>
<p>
 Na vaši účast se těší Správní rada „RB“VL a&nbsp;f. SPORT SERVIS.
</p>

<p>
 Frýdek-Místek<br>
 květen 2013
</p>