<p>
  <a class="btn btn-success" href="{link add}" title="Přidat příspěvek do diskuze"><span class="glyphicon glyphicon-plus"></span> Nový příspěvek</a>
</p>

{if !count($rows)}
<p>
  Nejsou uloženy žádné příspěvky
</p>
{else}

  <div class="row">
    {?$dataGrid->renderPaginator()}
  </div>

  {foreach $rows as $row}
    {if isset($user)}
      <div class="btn-group pull-right">
        <a class="btn btn-default" href="{link edit, $row->id}" title="upravit příspěvek"><span class="glyphicon glyphicon-pencil"></span></a>
        <a class="btn btn-default" href="{link delete, $row->id}" title="smazat příspěvek"><span class="glyphicon glyphicon-remove"></span></a>
      </div>
    {/if}
    <h4 class="clearfix">{$row->jmeno} <small>{$row->vlozeno|date:'%d.%m.%Y %H:%M'}</small></h4>

    {!$row->text |texy}

    {if !$iterator->last}
      <hr>
    {/if}
  {/foreach}

  <div class="row">
    {?$dataGrid->renderPaginator()}
  </div>

{/if}


