<p class="text-center">
  <a class="btn btn-success btn-lg" href="{link add}" title="Přidat příspěvek do diskuze"><span class="glyphicon glyphicon-plus"></span> Přidat příspěvek</a>
</p>

{if !count($rows)}
<p>
  Nejsou uloženy žádné příspěvky
</p>
{else}

  <div class="row">
    {?$dataGrid->renderPaginator()}
  </div>

  {foreach $rows as $row}
  <div class="panel-box">
    <div class="row">
      <div class="titles">
        <h4>
          {$row->jmeno} <small>{$row->vlozeno|date:'%d.%m.%Y %H:%M'}</small>
          {if isset($user)}
            <div class="btn-group pull-right">
              <a class="btn btn-default" href="{link edit, $row->id}" title="upravit příspěvek"><span class="glyphicon glyphicon-pencil"></span></a>
              <a class="btn btn-default" href="{link delete, $row->id}" title="smazat příspěvek"><span class="glyphicon glyphicon-remove"></span></a>
            </div>
          {/if}
        </h4>
      </div>
      <div class="col-md-12">
        {!$row->text |texy}
      </div>
    </div>
  </div>
  {/foreach}

  <div class="row">
    {?$dataGrid->renderPaginator()}
  </div>

{/if}


