<div class="row">
  <div class="col-md-6">
    <div class="panel-box">
      <div class="row">
        <div class="titles">
          <h4>Aktuální</h4>
        </div>
        <div class="col-md-12">
          <ul>
            <li><a href="{$baseUri}download/prihlaska_rbvl_1617.doc" title="Aktuální verze přihlášky">Přihláška pro ročník 2016-2017</a> (doc, 37 kB)</li>
            <li><a href="{$baseUri}download/soupiska_rbvl_1617.doc" title="Aktuální verze soupisky">Soupiska pro ročník 2016-2017</a> (doc, 84 kB)</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="panel-box">
      <div class="row">
        <div class="titles">
          <h4>Archiv</h4>
        </div>
        <div class="col-md-12">
          <ul>
            <li><a href="{$baseUri}download/archiv_rbvl_0910.zip">Výsledky a tabulky 1. ročníku 2009-2010</a> (zip, 685 kB)</li>
            <li><a href="{$baseUri}download/archiv_rbvl_1011.zip">Výsledky a tabulky 2. ročníku 2010-2011</a> (zip, 910 kB)</li>
            <li><a href="{$baseUri}download/archiv_rbvl_1112.zip">Výsledky a tabulky 3. ročníku 2011-2012</a> (zip, 1010 kB)</li>
            <li><a href="{$baseUri}download/archiv_rbvl_1213.zip">Výsledky a tabulky 4. ročníku 2012-2013</a> (zip, 685 kB)</li>
            <li><a href="{$baseUri}download/archiv-rbvl-1314.zip">Výsledky a tabulky 5. ročníku 2013-2014</a> (zip, 750 kB)</li>
            <li><a href="{$baseUri}download/archiv-rbvl-1415.zip">Výsledky a tabulky 6. ročníku 2014-2015</a> (zip, 335 kB)</li>
            <li><a href="{$baseUri}download/archiv-rbvl-1516.zip">Výsledky a tabulky 7. ročníku 2015-2016</a> (zip, 3.65 MB)</li>
            <li><a href="{$baseUri}download/archiv-rbvl-1617.zip">Výsledky a tabulky 8. ročníku 2016-2017</a> (zip, 485 kB)</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div> <!-- .row -->
