<p>
  <span class="glyphicon glyphicon-arrow-left"></span> <a href="{link default}">Zpět na družstva</a>
</p>
{!$form}

<h2>soupiska</h2>
<p id="infoNovy">Bude vytvořen nový hráč.</p>
<p id="infoEdit" style="display: none;">Bude editován existující hráč. <button type="button" class="btn btn-default" id="frmhracForm-reset">Storno</button></p>
{!$formSoupiska}


{if !count($soupiska)}
<p>
  Družstvo nemá na soupisce žádné hráče.
</p>
{else}
<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th>pořadí</th>
    <th>příjmení</th>
    <th>jméno</th>
    <th>datum narození</th>
    <th>&nbsp;</th>
  </tr>
  </thead>
  <tbody>
  {assign $poradi 1}
  {foreach $soupiska as $row}
    <tr>
      <td>{$poradi++}</td>
      <td>{$row->prijmeni}</td>
      <td>{$row->jmeno}</td>
      <td>{$row->narozen|date:'%d.%m.%Y'}</td>
      <td>
        <div class="pull-right">
          <a class="btn btn-default btn-xs" href="{link soupiskadelete, $row->idHrac, $druzstvo}" title="odebrat hráče {$row->prijmeni} {$row->jmeno} ze soupisky"><span class="glyphicon glyphicon-remove"></span></a>
        </div>
      </td>
    </tr>
  {/foreach}
  </tbody>
</table>
{/if}


<script>
  $(function() {
    if($( "#frmhracForm-hrac" ).val()) {
      $( "#infoNovy" ).hide();
      $( "#infoEdit" ).show();
    }
    else {
      $( "#infoNovy" ).show();
      $( "#infoEdit" ).hide();
    }
    var hraci = [
      {foreach $hraci as $row}
        { id: {$row->id}, value: {$row->prijmeni}, jmeno: {$row->jmeno}, narozen: {if $row->narozen} {$row->narozen|date:'%d.%m.%Y'} {else} "" {/if}},
      {/foreach}
    ];

    $( "#frmhracForm-prijmeni" ).autocomplete({
      minLength: 0,
      source: hraci,
      focus: function( event, ui ) {
        $( "#frmhracForm-prijmeni" ).val( ui.item.value );
        return false;
      },
      select: function( event, ui ) {
        $( "#frmhracForm-hrac" ).val( ui.item.id );
        $( "#frmhracForm-jmeno" ).val( ui.item.jmeno );
        $( "#frmhracForm-prijmeni" ).val( ui.item.value );
        $( "#frmhracForm-narozen" ).val( ui.item.narozen  );
        $( "#infoNovy" ).hide();
        $( "#infoEdit" ).show();
        return false;
      }
    })
    .data( "ui-autocomplete" )._renderItem = function( ul, item ) {
      return $( "<li>" )
        .append( "<a>" + item.value + " " + item.jmeno + ", " + item.narozen + "</a>" )
        .appendTo( ul );
    };
  });

  $( "#frmhracForm-reset" ).click(function() {
        $( "#frmhracForm-hrac" ).val("");
        $( "#frmhracForm-jmeno" ).val("");
        $( "#frmhracForm-prijmeni" ).val("");
        $( "#frmhracForm-narozen" ).val("");
        $( "#infoNovy" ).show();
        $( "#infoEdit" ).hide();
  });
</script>
