<div class="panel-box">
  <div class="row">
    <div class="col-md-12">

{if !count($druzstva)}
<p>
  Nejsou uložena žádná družstva.
</p>
{else}
  {foreach $druzstva as $druzstvo}
    {if $skupina != $druzstvo->skupina_popis}
      {if $skupina !=  ""}
        </ol>
      {/if}
      <h2>{$druzstvo->skupina_popis}</h2>
      <ol>
    {/if}
    <li>
      <p>
        {if isset($user)}
          <a class="btn btn-default " href="{link edit, $druzstvo->id}" title="upravit"><span class="glyphicon glyphicon-pencil"></span></a>
        {/if}
        <a href="{link soupiska, $druzstvo->id}" title="Soupiska druzstva {$druzstvo->nazev}">{$druzstvo->nazev}</a>
      </p>
    </li>
    {assign $skupina $druzstvo->skupina_popis}
    {if $iterator->isLast()}</ol>{/if}
  {/foreach}
{/if}
    </div>
  </div>
</div>
