{if isset($user)}
<p>
  <a class="btn btn-success" href="{plink Alba:add}" title="Přidat nové album"><i class="icon-plus icon-white"></i> Nové album</a>
</p>
{/if}

{if !count($alba)}
  <p>
    Fotogalerie neobsahuje žádná alba.
  </p>
{else}
  <ul class="thumbnails">
    {assign $i 0}
    {foreach $alba as $album}
      {assign $i $i+1}
      <li class="span2" {if ($i-1) % 4 == 0}style="clear: left"{/if}>
        <div class="thumbnail text-center">
          <a href="{plink Foto:album, $album->id}" title="{$album->popis}">
            <p>
             {if isset($album->soubor)}<img src="{$baseUri}photos/thumb_{$album->soubor}" alt="">{/if}
            </p>
            <p>
             {$album->popis}
            </p>
          </a>
          {if isset($user)}
            <div class="btn-group">
              <a class="btn btn-mini" href="{link Alba:edit, $album->id}" title="upravit"><i class="icon-pencil"></i></a>
              <a class="btn btn-mini" href="{link Alba:delete, $album->id}" title="smazat"><i class="icon-remove"></i></a>
            </div>
          {/if}
        </div>
      </li>
    {/foreach}
  </ul>
{/if}
