<div class="panel-box">
  <div class="row">
    <div class="col-md-12">

{if isset($user)}
<p class="text-center noPrint">
  <a class="btn btn-primary btn-lg" href="{plink Alba:add}" title="Přidat nové album"><span class="glyphicon glyphicon-plus"></span> Nové album</a>
</p>
{/if}

{if !count($alba)}
  <p>
    Fotogalerie neobsahuje žádná alba.
  </p>
{else}
  <ul class="thumbs">
    {foreach $alba as $album}
      <li>
        <a href="{plink Foto:album, $album->id}" title="{$album->popis}">
          <p>
           {if isset($album->soubor)}<img src="{$baseUri}photos/thumb_{$album->soubor}" alt="">{/if}
          </p>
        </a>
        <p>
         {$album->popis}
        </p>
        {if isset($user)}
          <div class="btn-group">
            <a class="btn btn-xs btn-default" href="{link Alba:edit, $album->id}" title="upravit"><span class="glyphicon glyphicon-pencil"></span></a>
            <a class="btn btn-xs btn-default" href="{link Alba:delete, $album->id}" title="smazat"><span class="glyphicon glyphicon-remove"></span></a>
          </div>
        {/if}
      </li>
    {/foreach}
  </ul>
{/if}
    </div>
  </div>
</div>
