<h3>{$album->popis}</h3>
<p>
  <i class="icon-arrow-left"></i> <a href="{link Foto:default}">Zpět do fotogalerie</a>
</p>
{if isset($user)}
<p class="flash">
  <a class="btn btn-success" href="{plink Foto:add, $album->id}" title="Přidat novou fotku do alba"><i class="icon-plus icon-white"></i> Nová fotka</a>
</p>
{/if}

{if !count($fotky)}
<p>
  Album neobsahuje žádné fotky.
</p>
{else}
  <p>
    Po kliknutí na náhled se fotografie otevře v plné velikosti.
  </p>

  <ul class="thumbnails">
    {assign $i 0}
    {foreach $fotky as $fotka}
      {assign $i $i+1}
      <li class="span2" {if ($i-1) % 4 == 0}style="clear: left"{/if}>
        <div class="thumbnail text-center">
          <p>
            <a href="{$baseUri}photos/{$fotka->soubor}" rel="lightbox[1]" title="{$fotka->popis}">
              <img src="{$baseUri}photos/thumb_{$fotka->soubor}" alt="{$fotka->popis}"  />
            </a>
          </p>
          <p>{$fotka->popis}</p>
          <div class="btn-group">
            {if isset($user)}
              <a class="btn btn-mini" href="{link Foto:edit, $fotka->id}" title="upravit"><i class="icon-pencil"></i></a>
              <a class="btn btn-mini" href="{link Foto:delete, $fotka->id}" title="smazat"><i class="icon-remove"></i></a>
            {/if}
            <a class="btn btn-mini" href="{link download, $fotka->id}" title="uložit"><i class="icon-download"></i> {if !isset($user)}uložit{/if}</a>
          </div>
        </div>
      </li>
    {/foreach}
  </ul>
{/if}
