<div class="panel-box">
  <div class="row">
    <div class="col-md-12">

{if isset($user)}
<p>
  <a class="btn btn-primary" href="{plink Alba:add}" title="Přidat nové album"><span class="glyphicon glyphicon-plus"></span> Nové album</a>
</p>
{/if}

{if !count($alba)}
  <p>
    Fotogalerie neobsahuje žádná alba.
  </p>
{else}
  <div class="row">
    {foreach $alba as $album}
      <div class="col-md-3">
        <div class="thumbnail text-center">
          <a href="{plink Foto:album, $album->id}" title="{$album->popis}">
            <p>
             {if isset($album->soubor)}<img src="{$baseUri}photos/thumb_{$album->soubor}" alt="">{/if}
            </p>
            <p>
             {$album->popis}
            </p>
          </a>
          {if isset($user)}
            <div class="btn-group">
              <a class="btn btn-xs btn-default" href="{link Alba:edit, $album->id}" title="upravit"><span class="glyphicon glyphicon-pencil"></span></a>
              <a class="btn btn-xs btn-default" href="{link Alba:delete, $album->id}" title="smazat"><span class="glyphicon glyphicon-remove"></span></a>
            </div>
          {/if}
        </div>
      </div>
    {/foreach}
  </div>
{/if}

    </div>
  </div>
</div>
