<h3>{$album->popis}</h3>
<p>
  <span class="glyphicon glyphicon-arrow-left"></span> <a href="{link Foto:default}">Zpět do fotogalerie</a>
</p>
{if isset($user)}
<p>
  <a class="btn btn-primary" href="{plink Foto:add, $album->id}" title="Přidat novou fotku do alba"><span class="glyphicon glyphicon-plus"></span> Nová fotka</a>
</p>
{/if}

{if !count($fotky)}
<p>
  Album neobsahuje žádné fotky.
</p>
{else}
  <p>
    Po kliknutí na náhled se fotografie otevře v plné velikosti.
  </p>

  <div class="row">
    {foreach $fotky as $fotka}
      <div class="col-md-3">
        <div class="thumbnail text-center">
          <p>
            <a href="{$baseUri}photos/{$fotka->soubor}" rel="lightbox[1]" title="{$fotka->popis}">
              <img src="{$baseUri}photos/thumb_{$fotka->soubor}" alt="{$fotka->popis}"  />
            </a>
          </p>
          <p>{$fotka->popis}</p>
          <div class="btn-group">
            {if isset($user)}
              <a class="btn btn-xs btn-default" href="{link Foto:edit, $fotka->id}" title="upravit"><span class="glyphicon glyphicon-pencil"></span></a>
              <a class="btn btn-xs btn-default" href="{link Foto:delete, $fotka->id}" title="smazat"><span class="glyphicon glyphicon-remove"></span></a>
            {/if}
            <a class="btn btn-xs btn-default" href="{link download, $fotka->id}" title="uložit"><span class="glyphicon glyphicon-floppy-disk"></span></a>
          </div>
        </div>
      </div>
    {/foreach}
  </div>
{/if}
