<div class="noPrint">
  <a class="btn btn-success" href="{link add}" title="Přidat nového hráče"><i class="icon-plus icon-white"></i> Nový hráč</a>
  <a class="btn btn-danger" href="{link clear}" title="Odebrat všechny hráče ze soupisek"><i class="icon-trash icon-white"></i> Vymazání soupisek</a>
</div>

{if !count($rows)}
<p>
  Databáze neobsahuje žádné hráče.
</p>
{else}



<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>příjmení</th>
      <th>jméno</th>
      <th>datum narození</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    {foreach $rows as $row}
      <tr>
        <td>{$row->prijmeni}</td>
        <td>{$row->jmeno}</td>
        <td>{$row->narozen|date:'%d.%m.%Y'}</td>
        <td>
          <div class="pull-right btn-group">
            <a class="btn btn-mini" href="{link edit, $row->id}" title="upravit hráče {$row->prijmeni} {$row->jmeno}"><i class="icon-pencil"></i></a>
            <a class="btn btn-mini" href="{link delete, $row->id}" title="smazat hráče {$row->prijmeni} {$row->jmeno}"><i class="icon-remove"></i></a>
          </div>
        </td>
      </tr>
    {/foreach}
  </tbody>
</table>



{/if}


