<h3>Vedoucí soutěže </h3>
<p>
  <strong>Werner Cigán</strong>
</p>
<dl class="dl-horizontal">
  <dt>telefon:</dt>
  <dd>724 218 568</dd>
  <dt>e-mail:</dt>
  <dd><a href="mailto:werner.cigan@email.cz">werner.cigan@email.cz</a></dd>
  <dt>adresa:</dt>
  <dd>Třanovského 388<br />738 01 Frýdek-Místek</dd>
</dl>

<h3>Správní rada</h3>
<p>
  <strong>Zdeněk Lička</strong>
</p>
<dl class="dl-horizontal">
  <dt>telefon:</dt>
  <dd>737 559 029</dd>
  <dt>e-mail:</dt>
  <dd><a href="mailto: zdenek.licka@c-mail.cz"> zdenek.licka@c-mail.cz</a></dd>
  <dt>adresa:</dt>
  <dd>Padlých hrdinů 1425<br>739 11 Frýdlant n. O.</dd>
</dl>
