<p>
  <strong>Werner Cigán</strong>
</p>
<p>
  předseda spolku „Beskydská volejbalová liga amatérů“ pověřený řízením soutěží
</p>
<dl class="dl-horizontal">
  <dt>telefon:</dt>
  <dd>724 218 568</dd>
  <dt>e-mail:</dt>
  <dd><a href="mailto:werner.cigan@email.cz">werner.cigan@email.cz</a></dd>
  <dt>adresa:</dt>
  <dd>Dr. M. Tyrše 3106<br />738 01 Frýdek-Místek</dd>
</dl>

<p>
  <strong>Zdeněk Lička</strong>
</p>
<p>
  místopředseda spolku „Beskydská volejbalová liga amatérů“ pověřený zastupováním řídícího soutěže
</p>
<dl class="dl-horizontal">
  <dt>telefon:</dt>
  <dd>737 559 029</dd>
  <dt>e-mail:</dt>
  <dd><a href="mailto:zdenek.licka@c-mail.cz">zdenek.licka@c-mail.cz</a></dd>
  <dt>adresa:</dt>
  <dd>Padlých hrdinů 1425<br>739 11 Frýdlant n. O.</dd>
</dl>

<p>
  <strong>Jiří Pomykal</strong>
</p>
<p>
  člen spolku „Beskydská volejbalová liga amatérů“ pověřený evidencí a&nbsp;kontrolou soupisek družstev
</p>
<dl class="dl-horizontal">
  <dt>telefon:</dt>
  <dd>732 864 608</dd>
  <dt>e-mail:</dt>
  <dd><a href="mailto:jiripomy@seznam.cz">jiripomy@seznam.cz</a></dd>
  <dt>adresa:</dt>
  <dd>V. Nezvala 549<br>738 01 Frýdek-Místek</dd>
</dl>
