<h2>Region Beskydy</h2>
<dl class="sponzori">
  <dt><a href="http://www.regionbeskydy.cz/" title="Region Beskydy"><img src="{$baseUri}images/logos/rb_logo.jpg" width="80px" height="100px" alt="Region Beskydy" /></a></dt>
  <dd><a href="http://www.regionbeskydy.cz/" title="Region Beskydy">http://www.regionbeskydy.cz</a></dd>
</dl>
<!--
<h2>Sport Servis</h2>
<dl class="sponzori">
  <dt><a href="http://www.sport-servis.me.cz/" title="SPORT SERVIS, Zdeněk Lička - široká nabídka sportovního zboží"><img src="{$baseUri}images/logos/sportservis_logo.jpg" width="120px" height="100px" alt="SPORT SERVIS, Zdeněk Lička - široká nabídka sportovního zboží" /></a></dt>
  <dd><a href="http://www.sport-servis.me.cz/" title="SPORT SERVIS, Zdeněk Lička - široká nabídka sportovního zboží">http://www.sport-servis.me.cz</a><br />
  SPORT SERVIS, Zdeněk Lička - široká nabídka sportovního zboží</dd>
</dl>

<h2>TJ Sokol Frýdek-Místek</h2>

<dl class="sponzori">
  <dt><a href="http://www.regionbeskydy.cz/" title="Region Beskydy"><img src="{$baseUri}images/logos/rb_logo.jpg" width="80px" height="100px" alt="Region Beskydy" /></a></dt>
  <dd><a href="http://www.regionbeskydy.cz/" title="Region Beskydy">http://www.regionbeskydy.cz</a></dd>
</dl>


<h2>Moravec - kvalitní ponožky</h2>
<dl class="sponzori">
  <dt><a href="http://www.moravec-cz.com/" title="Moravec - kvalitní ponožky. Vývoj, výroba a prodej ponožek"><img src="{$baseUri}images/logos/moravec_logo.jpg" width="210px" height="96px" alt="Moravec - kvalitní ponožky. Vývoj, výroba a prodej ponožek" /></a></dt>
  <dd><a href="http://www.moravec-cz.com/" title="Moravec - kvalitní ponožky. Vývoj, výroba a prodej ponožek">http://www.moravec-cz.com/</a><br />
  Moravec - kvalitní ponožky. Vývoj, výroba a prodej ponožek</dd>
</dl>

<h2>GLOBAL SPORT ČUPA s.r.o.</h2>
<dl class="sponzori">
  <dt><a href="http://www.gsport.cz/" title="GLOBAL SPORT ČUPA s.r.o. - zařízení a vybavení  pro různé sporty"><img src="{$baseUri}images/logos/gsport_logo.jpg" width="210px" height="100px" alt="GLOBAL SPORT ČUPA s.r.o. - zařízení a vybavení  pro různé sporty" /></a></dt>
  <dd><a href="http://www.gsport.cz/" title="GLOBAL SPORT ČUPA s.r.o. - zařízení a vybavení  pro různé sporty">http://www.gsport.cz/</a><br />
  Firma GLOBAL SPORT ČUPA s.r.o. působí v oboru sportovišť a sportovního vybavení</dd>
</dl>

-->

