<p>
  Pozn.: novinky v&nbsp;pravidlech jsou <mark>takto barevně zvýrazněny</mark>.
</p>

<h2>1. Základní ustanovení</h2>

<h3>1.1	Ustanovení</h3>

<p>
  „Region Beskydy“ volejbalovou ligu smíšených amatérských družstev (dále jen „RB“VL) pořádá a&nbsp;řídí spolek „Beskydská volejbalová liga amatérů“ se sídlem ve Frýdku-Místku na ulici V. Nezvala 549, IČ 02694409.
</p>
<p>
  Celou „RB“VL řídí tříčlenná správní rada. „RB“VL se řídí těmito pravidly. Případné doplňky těchto pravidel schvaluje správní rada.
</p>
<p>
  Oficiální webové stránky „RB“VL jsou www.rbvl.cz.
</p>

<h3>1.2 Cíl „RB“VL - Motto:</h3>
<p>
  <strong>Pojďme se bavit volejbalem v&nbsp; každém věku.</strong>
</p>

<h3>1.3 Struktura „RB“VL</h3>
<p>
  Nejvyšším orgánem „RB“VL je tříčlenná správní rada. Má veškeré pravomoci a&nbsp;jejich rozhodnutí je konečné.
</p>
<p>
  Hlavním úkolem správní rady je řízení „RB“VL, zejména organizace jednotlivých hracích termínů, řešení vzniklých nejasností a&nbsp;jako jediná s&nbsp;konečnou platnosti rozhoduje o&nbsp;pokutách a&nbsp;kontumačních výsledcích.
</p>
<p>
  <mark>
  Každý hrací den bude po celou dobu přítomen řídící soutěže, který bude dohlížet na chod hracího dne a&nbsp;bude rozhodovat o&nbsp;přestupech a&nbsp;hostování hráčů a&nbsp;řešit případné spory.
  </mark>
</p>

<h3>1.4	Pojištění</h3>

<p>
  Všichni účastníci „RB“VL startují na své vlastní zdravotní riziko a&nbsp;ze své zdravotní pojistky.
</p>


<h2>2. Startující družstva</h2>

<h3>2.1	Účastnicí „RB“VL</h3>

<p>
  Účastníkem soutěže se může stát jakékoliv družstvo, které splňuje pravidla „RB“VL, je řádně a&nbsp;včas přihlášeno, uhradilo startovné pro daný ročník a&nbsp;je správní radou do soutěže přijato.
</p>

<p>
  <mark>
  Družstvo může být přihlášeno pouze do jedné ligy v&nbsp;daném ročníku.
  </mark>
</p>

<p>
  Každé družstvo uvede v&nbsp;přihlášce název družstva, jméno a&nbsp;příjmení vedoucího družstva, který bude družstvo zastupovat a&nbsp;komunikovat se správní radou „RB“VL, a&nbsp;kontakt na něho (telefon, e-mail, případně adresu pro příjem pošty).
</p>

<h3>2.2 Registrovanost</h3>

<p>
  „RB“VL se nesmí zúčastnit hráči (muži), kteří v&nbsp;aktuálním soutěžním ročníku jsou uvedení na soupisce týmu hrajícího krajské a&nbsp;vyšší soutěže dospělých a&nbsp;ligové soutěže mládeže organizované ČVS. Registrování hráči družstev okresních a&nbsp;městských soutěží jsou pro „RB“VL považování za neregistrované.
</p>
<p>
<mark>
U žen se povoluje účast hráček hrajících krajské soutěže dospělých a ligové soutěže mládeže organizované ČVS.
</mark>
</p>
<p>
  U&nbsp;hráčů 40 letých a&nbsp;starších se registrovanost neposuzuje.
</p>
<p>
<mark>
Správní rada si vyhrazuje právo namátkové fyzické kontroly vybraného hráče nebo hráčky během hracího dne ve srovnání se soupiskou „RB“VL a následnou kontrolou registrovanosti.
</mark>
</p>

<h3>2.3 Smíšenost</h3>

<p>
  Družstvo musí nastoupit k&nbsp;utkání v&nbsp;6&nbsp;hráčích, z&nbsp;toho musí být alespoň 2 ženy (tzn. stanovené složení: 4m+2ž, 3m+3ž, 2m+4ž, 1m+5ž, 0m+6ž). Všichni hráči, kteří nastoupí k&nbsp;utkání, musí být uvedeni na soupisce družstva. Nastoupení družstva k&nbsp;utkání ve složení 6m+0ž nebo 5m+1ž je vyloučeno.
</p>

<h3>2.4	Soupiska</h3>
<p>
  Soupiska družstva může obsahovat libovolný počet hráčů. <strong>Každý hráč může v&nbsp;soupisce „RB“VL startovat pouze za jedno družstvo <mark>ve všech ligách</mark>.</strong>
</p>
<p>
  U&nbsp;všech hráčů musí být uvedeno datum narození (pro kontrolu registrovanosti) <mark>a&nbsp;každý hráč na soupisce svým podpisem udělí souhlas s&nbsp;možností publikovat v&nbsp;tisku a&nbsp;v&nbsp;elektronických médiích fotografie a&nbsp;videonahrávky z&nbsp;průběhu „RB“VL, které zachycují jeho osobu</mark>. U&nbsp;registrovaných hráčů musí být na soupisce uveden oddíl a&nbsp;soutěž, kterou hrají. Pokud bude zjištěno, že některé údaje na soupisce neodpovídají skutečnosti, či chybějí (např. tým u&nbsp;registrovaných), může vedení „RB“VL zakázat start hráči, u&nbsp;kterého došlo k&nbsp;pochybení, či potrestat družstvo za neoprávněný start takového hráče odebráním bodů.
</p>
<p>
  Vzhledem k&nbsp;možnosti uvést na soupisku libovolný počet hráčů, nebude možné žádat o&nbsp;případnou neúčast družstva na hracím dni z&nbsp;důvodů např. dovolených, školních prázdnin ap.
</p>

<h3>2.5 Dopisování hráčů na soupisku</h3>

<p>
  Hráč, který není na soupisce družstva hrajícího „RB“VL, může být dopsán na soupisku nejpozději <strong>před</strong> zahájením lednového (tj. čtvrtého) hracího dne. Po tomto termínu již dopisování není možné. <strong>Dopsání hráče provede pouze vedoucí družstva</strong>, <mark>zajistí podpis nového hráče na soupisku</mark>, a&nbsp;svým podpisem s&nbsp;datem ho potvrdí člen správní rady. Soupisky budou vedoucím družstev k&nbsp;dispozici vždy před zahájením každého z&nbsp;prvních čtyř hracích dnů.
</p>
<p>
  O&nbsp;dopsání hráče na soupisku lze předem požádat i&nbsp;e-mailem odeslaným na adresu:
<a href="mailto:werner.cigan@email.cz">werner.cigan@email.cz</a>. Na adresu odkud byla žádost odeslána, bude pak zasláno potvrzení o&nbsp;dopsání či zamítnutí s&nbsp;odůvodněním. <mark>Zapsání hráče do listinné soupisky s podpisy bude provedeno v následující hrací den.</mark>
</p>

<h3>2.6 Přestupy hráčů</h3>
<p>
  Přestup je možné uskutečnit nejpozději <strong>před</strong> zahájením lednového (tj.čtvrtého) hracího dne. O&nbsp;přestup musí požádat hráč, jehož se to týká a&nbsp;to zásadně se souhlasem příslušného vedoucího družstva odkud hráč přestupuje.
</p>
<p>
  Změnu na obou soupiskách (vyškrtnutí ze soupisky družstva, z&nbsp;něhož hráč přestupuje a&nbsp;dopsání na soupisku družstva, do kterého hráč přestupuje) provede řídící soutěže. Obě soupisky potvrdí svým podpisem a&nbsp;datem uskutečněného přestupu.
</p>
<p>
  Soupisky budou vedoucím družstev k&nbsp;dispozici vždy před zahájením každého z&nbsp;prvních čtyř hracích dnů. Jiný termín je třeba domluvit s&nbsp;řídícím soutěže.
</p>

<h3>2.7 Hostování</h3>
<p>
  Nastoupit k&nbsp;utkání <mark>v neúplném složení nebo</mark> s&nbsp;pěti hráči je v&nbsp;„RB“VL nepřípustné!
</p>
<p>
  V&nbsp;případě, že se družstvo dostaví v&nbsp;příslušném hracím dni k&nbsp;odehrání svých utkání <mark>v neúplném složení nebo</mark> pouze s&nbsp;pěti hráči, oznámí neprodleně tuto skutečnost <span>řídícímu soutěže</mark>, který je vždy přítomen.
</p>
<p>
  Družstvu se umožní dohodnout se s&nbsp;jinými přítomnými družstvy o&nbsp;startu jejich hráče nebo hráčky za neúplné družstvo na tzv. „hostování“. Tím se rozumí, že se příslušný hráč či hráčka, který dosud v&nbsp;tento den nenastupoval za své družstvo, stává členem neúplného družstva po celý hrací den. Tzn., že s&nbsp;ním odehraje všechna utkání! Za své původní družstvo v&nbsp;tento den nastoupit nesmí. <mark>Hostování schvaluje a&nbsp;provádí řídící soutěže.</mark>
</p>
<p>
  Před každým utkáním uvede řídící soutěže „hostování“ do zápisu o&nbsp;utkání (jméno hráče/hráčky a&nbsp;název původního družstva). Zápis podepíší kapitáni obou družstev a&nbsp;rozhodčí utkání.
</p>


<h2>3. Systém soutěže</h2>


<h3>3.1 Základní pravidla</h3>

<p>
  Hraje se dle platných pravidel volejbalu.
</p>

<h3>3.2 Hrací systém</h3>

<p>
  „RB“VL je organizovaná jako dlouhodobá soutěž s&nbsp;jedním hracím dnem v&nbsp;měsíci (říjen až březen). Veškeré zápasy budou odehrány v&nbsp;hale na třech kurtech.
</p>
<p>
  „RB“VL je organizována rozdělením družstev do Ligy „A“ a&nbsp;Ligy „B“. V&nbsp;Lize „A“ startují družstva, která si účast vybojovala v předchozím ročníku. V&nbsp;Lize „B“ startují družstva ostatní, včetně nově přihlášených. Liga „A“ je omezena počtem 16 účastníků. Liga „B“ je soutěží otevřenou a&nbsp;počet družstev se nelimituje.
</p>
<p>
  Pokud se některé družstvo z&nbsp;Ligy „A“ nepřihlásí nebo požádá o&nbsp;zařazení do Ligy „B“, nabídne pořadatel možnost startovat v&nbsp;Lize „A“ družstvům sestupujícím z&nbsp;předchozího ročníku „RB“VL, Ligy „A“ (14., 15. a&nbsp;16. místo).
</p>
<p>
  Utkání se hrají na 2 vyhrané sety do 25 bez ztrát (konec setu rozdílem 2 bodů). Třetí set je zkrácen do 15&nbsp;bodů (konec setu rozdílem 2 bodů).
</p>
<p>
  Liga „A“ a&nbsp;liga „B“ se hrají v&nbsp;samostatných termínech.
</p>
<p>
  Liga „A“ o&nbsp;16 účastnících se odehraje systémem každý s&nbsp;každým v&nbsp;pěti termínech, přičemž v&nbsp;každém termínu odehraje jedno družstvo 3 utkání. O&nbsp;konečném pořadí se rozhodne v&nbsp;závěrečném šestém termínu systémem jednokolového play&nbsp;off o&nbsp;1. až 8. místo a&nbsp;o 9. až 16. místo.
</p>
<p>
  Liga „B“ se odehraje hracím systémem, který určí pořadatel dle počtu přihlášených družstev.
</p>
<p>
  Přesný herní systém bude popsán v&nbsp;ROZPISU „RB“VL, který bude k&nbsp;dispozici na oficiálních webových stránkách a&nbsp;na každém hracím dnu u&nbsp;pořadatelů.
</p>

<h3>3.3 Sestupy a&nbsp;postupy</h3>
<p>
  Družstva na 14., 15. a&nbsp;16. místě v&nbsp;konečném pořadí Ligy „A“ sestoupí do Ligy „B“. Naopak 3 nejlepší družstva z&nbsp;Ligy „B“ postoupí do Ligy „A“ pro následující ročník.
</p>


<h3>3.4 Bodování</h3>
<p>
  Družstva si za zápasy připisuji tyto body do tabulky:
</p>
<ul>
<li>3 body za vítězství 2 : 0</li>
<li>2 body za vítězství 2 : 1</li>
<li>1 bod za prohru 1 : 2</li>
<li>0 bodu za prohru 0 : 2</li>
<li>-1 bod za kontumaci</li>
</ul>

<h3>3.5 Rozhodčí</h3>
<p>
  Všechny zápasy budou pískat delegování rozhodčí.
</p>


<h3>3.6 Začátky zápasů</h3>
<p>
<mark>
  Orientační čas začátku jednotlivých utkání je uveden v&nbsp;herním systému. Skutečný čas začátku utkání je vyhlášen delegovaným rozhodčím minimálně 5 minut předem.
</mark>
</p>
<p>
  Družstva se dostaví k&nbsp;zápasu alespoň 5 minut před stanoveným začátkem. Čekací doba je 10 minut od stanoveného začátku, poté může být zápas řídícím soutěže „RB“VL kontumován ve prospěch čekajícího družstva. Není-li přítomno ani jedno družstvo, řídící soutěže „RB“VL kontumuje zápas oběma družstvům.
</p>
<p>
  Družstva mají nárok na 5 minutové rozcvičení před začátkem utkání.
</p>

<h3>3.7 Zápis o&nbsp;utkání</h3>

<p>
  Rozhodčí mají povinnost ke každému utkání vyhotovit „Zápis o&nbsp;utkání“ a&nbsp;po utkání ho odevzdat řídícímu soutěže. Tento dokument získá rozhodčí před utkáním od řídícího soutěže.
</p>

<p>
  Zápis o&nbsp;utkání kromě bodů a&nbsp;výsledku obsahuje:
</p>
<ul>
<li>podpisy kapitánů a&nbsp;rozhodčího po utkání,</li>
<li>případné protesty kapitánů proti porušení pravidel „RB“VL,</li>
<li><mark>záznamy o hostování.</mark></li>
</ul>


<h3>3.8 Výsledky</h3>

<p>
  Výsledky, průběžné pořadí a&nbsp;další informace zveřejňuje správní rada „RB“VL na oficiálních internetových stránkách a&nbsp;to nejpozději do dvou dnů od uskutečnění hracího dne.
</p>

<h3>3.9 Hra s&nbsp;liberem</h3>
<p>
  Pravidla dovolují hrát až se&nbsp;dvěma libery. Pro „RB“VL to mohou být <mark>buď 1 muž nebo 2 muži a 1 žena nebo 2 ženy</mark>. Jejich start je stanoven těmito podmínkami:
</p>
<ul>
  <li><strong>Družstvo musí nastoupit jednotně oblečeno, přičemž libero (libera) musí nastoupit ve výrazně barevně odlišném dresu.</strong></li>
  <li>Liberem se myslí pouze hráč či hráčka, který bude ve svém postavení střídat pouze hráče či hráčku tak, aby bylo zachováno stanovené složení družstva tj. 6 hráčů, z toho min. 2 ženy (4m+2ž, 3m+3ž, 2m+4ž, 1m+5ž, 0m+6ž). Libero střídá pouze hráče (hráčky) zadní řady!</li>
  <li>Družstvo, které nastoupí s&nbsp;liberem, musí tuto skutečnost oznámit před zahájením utkání rozhodčímu.</li>
  <li>Rozhodčí neumožní družstvu start s&nbsp;liberem, pokud nebudou dodrženy podmínky ustrojení družstva s&nbsp;liberem a&nbsp;stanoveného složení družstva.</li>
  <li>Správní rada schvaluje výjimku z&nbsp;Pravidel volejbalu takto:<br>
  Pokud družstvo nastoupí se šesti hráči + libero a&nbsp;v průběhu utkání dojde ke zranění hráče, povoluje se ihned nahradit zraněného hráče liberem. Zraněný hráč se již do konce utkání nemůže vrátit do hry. <strong>Zároveň musí být dodržen čl. 2.3 Smíšenost!</strong></li>
</ul>

<h3>3.10 Družstva „neúplná“ a&nbsp;„nepřítomná“</h3>
<p>
  Správní rada znovu upozorňuje, že hrát „RB“VL v&nbsp;neúplném složení nebo s&nbsp;pěti hráči je nepřípustné, i&nbsp;kdyby s&nbsp;tím jakkoliv soupeř souhlasil. Pokud se družstvo dostaví ke svým zápasům s&nbsp;pěti hráči nebo nemá minimálně 2 ženy, může tento problém vyřešit před svým <strong>prvním</strong> utkáním pomocí čl. 2.7 Hostování.
</p>
<p><strong>Řešení situace, kdy družstvo nastoupí s&nbsp;minimálním počtem hráčů:</strong></p>
<ul>
 <li>a) Družstvo nastoupilo s minimálním počtem hráčů ve stanoveném složení (čl.&nbsp;2.3&nbsp;Smíšenost) a&nbsp;zranil se hráč. Družstvo se stalo <strong>„neúplným“</strong> a&nbsp;postup je takový, že rozhodčí dopíše stav setů tak, aby výsledek byl buď 2:0, nebo 2:1 pro soupeře. Uvedené výsledky se stávají platnými a&nbsp;vítěz získává 3, nebo 2 body. Poražení 1, nebo 0 bodů. <strong>Utkání není kontumováno!</strong></li>
 <li>b) Družstvo nemá stanovené složení nebo má pro další utkání pouze 5 hráčů a&nbsp;hostování již nelze uplatnit. Stává se tzv. <strong>„nepřítomným“</strong> a&nbsp;<strong>prohrává své utkání kontumačně</strong> 0:2 (0:50) a&nbsp;do tabulky se započítává -1 bod.</li>
</ul>

<h3>3.11 Sportovní výstroj</h3>
<p>
<mark>
  Hráči musí nastoupit ke hře ve sportovní sálové obuvi.
</mark>
</p>
<p>
<mark>
  Správní rada doporučuje jednotné oblečení, myslí se tím především jednotné dresy (trička), případně i trenýrky, dresy pokud možno i s čísly.
</mark>
</p>
<p>
<mark>
  V případě využívání libera musí nastoupit příslušné družstvo k utkání v jednotném ustrojení a libero musí nastoupit k utkání ve výrazně odlišném dresu (viz čl. 3.9 Hra s liberem)!
</mark>
</p>


<h3>3.12 Volba hracího míče</h3>
<p>
 V&nbsp;„RB“VL je hracím míčem GALA Official BV 5591S. Hrací míče zajišťuje pořadatel „RB“VL.
</p>

<h3>3.13 Zapisovatel</h3>
<p>
 Vedení zápisu utkání včetně ovládání ukazatele skóre se ujme někdo z&nbsp;nehrajících hráčů jednoho či druhého družstva. V&nbsp;případě, že obě družstva nastoupí k&nbsp;utkání s&nbsp;minimálním počtem 6 hráčů, vyřeší zapisovatele sama družstva požádáním kohokoliv z&nbsp;nehrajících družstev.
</p>

<h2>4. Spory a&nbsp;tresty</h2>

<h3>4.1 Neúčast</h3>

<p>
  Neúčast družstva na hracím dnu je neomluvitelná. Za tento prohřešek družstvo uhradí pořádkovou pokutu 300&nbsp;Kč a&nbsp;kontumačně prohrává zápasy hracího dne (ostatní družstva jsou totiž poškozená změnami v&nbsp;rozpisu hracího dne, které vznikly vyřazením zápasu v&nbsp;rozpisu).
</p>
<p>
  Za opakovanou neúčast bude družstvo ze soutěže vyloučeno.
</p>


<h3>4.2 Spory</h3>
<p>
  Protest proti porušení pravidel „RB“VL je možno podat před podpisem Zápisu o&nbsp;utkání kapitánem družstva. Tento protest je nutno zaznamenat do Zápisu o&nbsp;utkání písemně a&nbsp;to za přítomnosti rozhodčího. Stvrzením Zápisu o&nbsp;utkání bez podaného protestu se výsledek stává platným a&nbsp;nelze se proti němu odvolat.
</p>
<p>
  Veškeré spory řeší správní rada „RB“VL. Rozhodnutí rady je konečné a&nbsp;nelze se proti němu odvolat.
</p>


<h2>5. Závěrečné ustanovení</h2>


<h3>5.1 Vedení soutěže</h3>

<p>
<mark>
  „RB“VL je řízená správní radou, kterou tvoří členové spolku „Beskydská volejbalová liga amatérů“:
</mark>
</p>
<ul>
  <li>Werner Cigán - předseda spolku pověřený řízením soutěže</li>
  <li>Zdeněk Lička - místopředseda spolku pověřený zastupováním řídícího soutěže</li>
  <li>Jiří Pomykal - člen spolku pověřený evidencí a kontrolou soupisek družstev a zastupováním řídícího soutěže</li>
</ul>


<p>
  Správní rada si vyhrazuje právo na změnu pravidel tak, aby byl zabezpečen hladký a&nbsp;bezproblémový průběh „RB“VL.
</p>
<p>
  Případné změny musí být zaslány či předány správní radě nejpozději před zahájením hracího dne, od něhož změny platí.
</p>
<p>
  Správní rada rozhoduje o&nbsp;všech záležitostech neuvedených v&nbsp;těchto PRAVIDLECH, jakož i&nbsp;o dalších problémech vzniklých v&nbsp;jednotlivých hracích dnech.
</p>


<h3>5.2 Platnost pravidel</h3>
<p>
  Tato pravidla jsou platná od 1.6.2015
</p>


<br /><br />
<p>
  Ve Frýdku Místku dne 20. května 2015
</p>