<p>
  Pozn.: novinky v&nbsp;pravidlech jsou <span class="highlight">takto barevně zvýrazněny</span>.
</p>

<h3>1. Základní ustanovení</h3>

<h4>1.1	Ustanovení</h4>

<p>
  „Region Beskydy“ volejbalovou ligu smíšených amatérských družstev („RB“VL) <span class="highlight">vyhlašuje SPORT SERVIS&nbsp;-&nbsp;Zdeněk Lička, Frýdlant n. O. (IČ: 45220417)</span>.
</p>
<p>
  Celou „RB“VL řídí pětičlenná rada složená se zástupců pořadatele.
„RB“VL se řídí těmito pravidly. Případné výjimky z&nbsp;těchto pravidel a&nbsp;jejich úpravu schvaluje řídící rada ligy.
</p>

<h4>1.2   Cíl  „RB“VL  - Motto:</h4>
<p class="alert alert-success">
  <strong>Pojďme  se  bavit  volejbalem  v&nbsp; každém  věku.</strong>
</p>


<h4>1.3    Struktura  „RB“VL</h4>
<p>
  Nejvyšším orgánem „RB“VL je pětičlenná řídící rada. Má veškeré pravomoci a&nbsp;jejich rozhodnutí je konečné.
</p>
<p>
  Hlavním úkolem rady je řízení „RB“VL, zejména organizace jednotlivých hracích termínů, řešení vzniklých nejasností a&nbsp;jako jediná s&nbsp;konečnou platnosti rozhoduje o&nbsp;pokutách a&nbsp;kontumačních výsledcích.
</p>

<h4>1.4	Pojištění</h4>

<p>
  Všichni účastníci „RB“VL startují na své vlastní zdravotní riziko a&nbsp;ze své zdravotní pojistky.
</p>


<h3>2. Startující družstva</h3>

<h4>2.1	Účastnicí „RB“VL</h4>

<p>
  Účastníkem soutěže se může stát jakékoliv družstvo, které splňuje pravidla „RB“VL, je řádně a&nbsp;včas přihlášeno, uhradilo startovné pro daný ročník a&nbsp;je radou do soutěže přijato.
</p>

<p>
  Každé družstvo uvede v&nbsp;přihlášce název družstva, jméno a&nbsp;příjmení vedoucího družstva (který bude družstvo zastupovat a&nbsp;komunikovat s&nbsp;vedením „RB“VL)  a&nbsp;kontakt na něho (telefon, e-mail, případně adresu pro příjem pošty).
</p>

<h4>2.2    Registrovanost</h4>

<p>
  „RB“VL se nesmí zúčastnit hráči <span class="highlight">(muži)</span>, kteří v&nbsp;aktuálním soutěžním ročníku jsou uvedení na soupisce týmu hrajícího krajské a&nbsp;vyšší soutěže dospělých a&nbsp;ligové soutěže mládeže organizované ČVS. Registrování hráči družstev okresních a&nbsp;městských soutěží jsou pro „RB“VL považování za neregistrované.
U žen se povoluje účast hráček hrajících krajské soutěže dospělých a&nbsp;ligu juniorek.
</p>
<p>
  U&nbsp;hráčů 40-ti letých a&nbsp;starších se registrovanost neposuzuje.
</p>


<h4>2.3  Smíšenost</h4>

<p>
  Družstvo musí nastoupit k&nbsp;utkání v&nbsp;6 hráčích, z&nbsp;toho musí být alespoň 2 ženy (tzn. 4m+2ž, 3m+3ž, 2m+4ž, 1m+5ž, 0m+6ž). Všichni hráči, kteří nastoupí k&nbsp;utkání, musí být na soupisce družstva. Nastoupení družstva k&nbsp;utkání ve složení 6m+0ž nebo 5m+1ž je vyloučeno.
</p>

<h4>2.4	Soupiska</h4>
<p>
  Soupiska družstva muže obsahovat libovolný počet hráčů. <strong>Každý hráč může v&nbsp;soupisce „RB“VL startovat pouze za jedno družstvo.</strong>
</p>
<p>
  U&nbsp;všech hráčů musí být uvedeno datum  narození (pro kontrolu registrovanosti). U&nbsp;registrovaných hráčů musí být na soupisce uveden oddíl a&nbsp;soutěž, kterou hrají. Pokud bude zjištěno, že některé údaje na soupisce neodpovídají skutečnosti, či chybějí (např. tým u&nbsp;registrovaných), může vedení „RB“VL zakázat start hráči, u&nbsp;kterého došlo k&nbsp;pochybení, či potrestat družstvo za neoprávněný start takového hráče odebráním bodů.
</p>
<p>
  Vzhledem k&nbsp;možnosti uvést na soupisku libovolný počet hráčů, nebude možné žádat o&nbsp;případnou neúčast družstva na hracím dnů z&nbsp;důvodů např. dovolených, školních prázdnin ap.
</p>

<h4>2.5    Dopisování hráčů na soupisku</h4>

<p>
  Hráč, který není na soupisce družstva hrajícího „RB“VL, může být dopsán na soupisku nejpozději  <strong>před</strong>  zahájením lednového (tj. čtvrtého) hracího dne. Po tomto termínu již dopisování není možné. Dopsání hráče provede vedoucí družstva a&nbsp;svým podpisem s&nbsp;datem ho potvrdí člen rady. Soupisky budou vedoucím družstev k&nbsp;dispozici vždy před zahájením každého z&nbsp;prvních čtyř hracích dnů.
</p>
<p>
  O&nbsp;dopsání hráče na soupisku lze požádat i&nbsp;e-mailem odeslaným na:
<a href="mailto:werner.cigan@email.cz">werner.cigan@email.cz</a>. Na adresu odkud byla žádost odeslána bude pak zasláno potvrzení o&nbsp;dopsání či zamítnutí s&nbsp;odůvodněním.
</p>

<h4>2.6    Přestupy hráčů</h4>
<p>
  Přestup je možné  uskutečnit nejpozději  <strong>před</strong>  zahájením  lednového  (tj.čtvrtého) hracího dne. O&nbsp;přestupu musí zažádat hráč, jehož se to týká a&nbsp;musí s&nbsp;ním souhlasit vedoucí družstva, kam hráč přestupuje. Na obou soupiskách musí změnu potvrdit podpisem s&nbsp;datem. Přestup poté musí oznámit kapitánovi družstva, odkud hráč přestupoval.
</p>
<p>
  Soupisky budou vedoucím družstev k&nbsp;dispozici vždy před zahájením každého z&nbsp;prvních čtyř hracích dnů. Jiný termín je třeba domluvit s&nbsp;příslušným členem rady.
</p>

<h4>2.7    Hostování</h4>
<p>
  Nastoupit k&nbsp;utkání s&nbsp;pěti hráči je v&nbsp;„RB“VL nepřípustné!
</p>
<p>
  V&nbsp;případě, že se družstvo dostaví v&nbsp;příslušném hracím dni k&nbsp;odehrání svých tří utkání pouze s&nbsp;pěti hráči, oznámí neprodleně tuto skutečnost členu správní rady, který je vždy přítomen.
</p>
<p>
  Družstvu se umožní dohodnout se s&nbsp;jinými přítomnými družstvy o&nbsp;startu jejich hráče nebo hráčky za neúplné družstvo na tzv. „hostování“. Tím se rozumí, že se příslušný hráč či hráčka stává členem neúplného družstva po celý hrací den. Tzn., že s&nbsp;ním odehraje všechna utkání! Za své původní družstvo v&nbsp;tento den nastoupit nesmí.
</p>
<p>
  Před každým utkáním se uvede „hostování“ do zápisu o&nbsp;utkání (jméno hráče/hráčky a&nbsp;název původního družstva). Zápis podepíší kapitáni obou družstev a&nbsp;rozhodčí utkání.
</p>


<h3>3. Systém soutěže</h3>


<h4>3.1    Základní pravidla</h4>

<p>
  Hraje se dle platných mezinárodních pravidel volejbalu.
</p>

<h4>3.2     Hrací systém</h4>

<p>
  „RB“VL je organizovaná jako dlouhodobá soutěž s&nbsp;jedním hracím dnem v&nbsp;měsíci (říjen až březen). Veškeré zápasy budou odehrány v&nbsp;hale na třech kurtech.
</p>
<p>
  Od 2. ročníku je „RB“VL organizována rozdělením družstev do Ligy „A“ a&nbsp;Ligy „B“. V&nbsp;Lize „A“ startují družstva, která si účast vybojovala ve 4. ročníku. V&nbsp;Lize „B“ budou startovat  družstva ostatní, včetně nově přihlášených. Liga „A“ je omezena počtem 16-ti účastníků. Liga „B“ je soutěží otevřenou a&nbsp;počet družstev se nelimituje.
</p>
<p>
  Pokud se některé družstvo z&nbsp;Ligy „A“ nepřihlásí nebo požádá o&nbsp;zařazení do Ligy „B“, nabídne pořadatel možnost startovat v&nbsp;Lize „A“ družstvům sestupujícím ze&nbsp;4. ročníku „RB“VL (14., 15. a&nbsp;16. místo).
</p>
<p>
  Utkání se hrají na 2 vyhrané sety do 25 bez ztrát (konec setu rozdílem 2 bodů). Třetí set je zkrácen do 15&nbsp;bodů (konec setu rozdílem 2 bodů).
</p>
<p>
  Liga „A“ a&nbsp;liga „B“ se hrají v&nbsp;samostatných termínech.
</p>
<p>
  <strong>Liga „A“</strong> o&nbsp;16 účastnících se odehraje systémem každý s&nbsp;každým v&nbsp;pěti termínech, přičemž v&nbsp;každém termínu odehraje jedno družstvo 3 utkání. O&nbsp;konečném pořadí se rozhodne v&nbsp;závěrečném šestém termínu systémem jednokolového play off o&nbsp;1. až 8. místo a&nbsp;o 9. až 16. místo.
</p>
<p>
  <strong>Liga „B“</strong> se odehraje hracím systémem, který určí pořadatel dle počtu přihlášených družstev.
</p>
<p>
  Přesný herní systém bude popsán  v&nbsp; ROZPISU  „RB“VL, který obdrží každý vedoucí družstva před zahájením soutěže a&nbsp;který bude k&nbsp;dispozici na webových stránkách a&nbsp;na každém hracím dnu u&nbsp;pořadatelů.
</p>

<h4>3.3    Sestupy a&nbsp;postupy</h4>
<p>
  Družstva na 14., 15. a&nbsp;16. místě v&nbsp;konečném pořadí Ligy „A“ sestoupí do Ligy „B“. Naopak 3 nejlepší družstva z&nbsp;Ligy „B“ postoupí do Ligy „A“ ročníku 2014-2015.
</p>


<h4>3.4    Bodování</h4>
<p>
  Družstva si za zápasy připisuji tyto body do tabulky:
</p>
<ul>
<li>3 body za vítězství 2 : 0</li>
<li>2 body za vítězství 2 : 1</li>
<li>1 bod za prohru 1 : 2</li>
<li>0 bodu za prohru 0 : 2</li>
<li>-1 bod za kontumaci</li>
</ul>

<h4>3.5     Rozhodčí</h4>
<p>
  Všechny zápasy budou pískat delegování rozhodčí.
</p>


<h4>3.6     Začátky zápasů</h4>
<p>
  Družstva se dostaví k&nbsp;zápasu alespoň 5 minut před stanoveným začátkem. Čekací doba je 10 minut od stanoveného začátku, poté může být zápas vedením  „RB“VL  kontumován  ve prospěch čekajícího družstva. Není-li přítomno ani jedno družstvo, vedení „RB“VL kontumuje zápas oběma družstvům.
</p>
<p>
  Družstva mají nárok na 5ti minutové rozcvičení.
</p>

<h4>3.7     Zápis o&nbsp;utkání</h4>

<p>
  Rozhodčí mají povinnost ke každému utkání vyhotovit „Zápis o&nbsp;utkání“ a&nbsp;po utkání ho odevzdat pořadatelům soutěže. Tento dokument získá rozhodčí před utkáním od pořadatelů soutěže.
</p>

<p>
  Zápis o&nbsp;utkání kromě bodů a&nbsp;výsledku obsahuje:
</p>
<ul>
<li>podpisy kapitánů a&nbsp;rozhodčího po utkání</li>
<li>případné protesty kapitánů proti porušení pravidel  „RB“VL</li>
</ul>


<h4>3.8    Výsledky</h4>

<p>
  Výsledky, průběžné pořadí a&nbsp;další informace zveřejňují pořadatelé soutěže na těchto internetových stránkách a&nbsp;to nejpozději do dvou dnů od uskutečnění hracího dne.
</p>

<h4>3.9    Hra s&nbsp;liberem</h4>
<p>
  <span class="highlight">Pravidla dovolují hrát až se&nbsp;dvěma libery. Pro „RB“VL to mohou být buď 2 muži, nebo 1 muž a&nbsp;1 žena.</span> Jejich start je stanoven těmito podmínkami:
</p>
<ul>
  <li>Družstvo musí nastoupit jednotně oblečeno, přičemž libero (libera) musí nastoupit ve výrazně barevně odlišném dresu (platí pro Ligu „A“ i&nbsp;Ligu „B“).</li>
  <li>Liberem se myslí pouze hráč či hráčka, který bude ve svém postavení střídat pouze hráče či hráčku tak, aby bylo zachováno složení družstva 4 muži + 2 ženy, případně 3 muži + 3 ženy, či 2 muži + 4 ženy. Libero střídá pouze hráče (hráčky) zadní řady!</li>
  <li>Družstvo, které nastoupí s&nbsp;liberem, musí tuto skutečnost oznámit před zahájením utkání rozhodčímu.</li>
  <li class="highlight">Pořadatel schvaluje výjimku z&nbsp;Pravidel volejbalu takto:<br>
  Pokud družstvo nastoupí se šesti hráči + libero a&nbsp;v průběhu utkání dojde ke zranění hráče, povoluje se ihned nahradit zraněného hráče liberem. Zraněný hráč se již do konce utkání nemůže vrátit do hry. <strong>Zároveň musí být dodržen čl. 2.3 Smíšenost!</strong></li>
</ul>

<h4>3.10    Družstva „neúplná“ a&nbsp;„nepřítomná“</h4>
<p class="highlight">
  Pořadatel znovu upozorňuje, že hrát „RB“VL s&nbsp;pěti hráči je nepřípustné, i&nbsp;kdyby s&nbsp;tím jakkoliv soupeř souhlasil. Pokud se družstvo dostaví ke svým zápasů s&nbsp;pěti hráči, může tento problém vyřešit před svým <strong>prvním</strong> utkáním pomocí čl. 2.7 Hostování.
</p>
<p class="highlight"><strong>Řešení situace, kdy družstvo nastoupí pouze se šesti hráči:</strong></p>
<ul>
 <li class="highlight">A) Družstvo nastoupilo pouze se šesti hráči (4+2) a&nbsp;zranil se hráč. Družstvo se stalo <strong>„neúplným“</strong> a&nbsp;postup je takový, že rozhodčí dopíše stav setů tak, aby výsledek byl buď 2:0, nebo 2:1 pro soupeře. Uvedené výsledky se stávají platnými a&nbsp;vítěz získává 3, nebo 2 body. Poražení 1, nebo 0 bodů. <strong>Utkání není kontumováno!</strong></li>
 <li class="highlight">B) Družstvo má pro další utkání pouze 5 hráčů a&nbsp;hostování již nelze uplatnit. Stává se tzv. <strong>„nepřítomným“</strong> a&nbsp;&nbsp;<strong>prohrává své utkání kontumačně</strong> 0:2 (0:50) a&nbsp;do tabulky se započítává -1 bod.</li>
</ul>

<h4>3.11    Sportovní výstroj</h4>
<p>
  Od ročníku 2011-2012 je <strong>povinností družstev startujících v&nbsp;Lize „A“ nastupovat k&nbsp;utkáním v&nbsp;jednotném ustrojení</strong>. Myslí se tím především jednotné dresy (trička), případně i&nbsp;trenýrky. Dresy pokud možno i&nbsp;s čísly.
</p>
<p>
  V&nbsp;Lize „B“ pořadatel <strong>doporučuje</strong> jednotné oblečení.
</p>
<p>
  Libero musí nastoupit k&nbsp;utkání ve <strong>výrazně</strong> odlišném dresu.
</p>


<h4>3.12    Volba hracího míče</h4>
<p class="highlight">
 V&nbsp;„RB“VL je hracím míčem GALA Official BV 5591S. Hrací míče zajišťuje pořadatel „RB“VL.
</p>

<h4>3.13  Zapisovatel</h4>
<p>
 Vedení zápisu utkání včetně ovládání ukazatele skóre se ujme někdo z&nbsp;nehrajících hráčů jednoho či druhého družstva. V&nbsp;případě, že obě družstva nastoupí k&nbsp;utkání s&nbsp;minimálním počtem 6-ti hráčů, vyřeší zapisovatele sama družstva požádáním kohokoliv z&nbsp;nehrajících družstev.
</p>

<h3>4. Spory a&nbsp;tresty</h3>

<h4>4.1     Neúčast</h4>

<p>
  Neúčast družstva na hracím dnu je neomluvitelná. Za tento prohřešek družstvo uhradí pořádkovou pokutu 300,- Kč a&nbsp;kontumačně prohrává zápasy hracího dne (ostatní družstva jsou totiž poškozená změnami v&nbsp;rozpisu hracího dne, které vznikly vyřazením zápasu v&nbsp;rozpisu).
</p>
<p>
  Za opakovanou neúčast bude družstvo ze soutěže vyloučeno.
</p>


<h4>4.2     Spory</h4>
<p>
  Protest proti porušení pravidel  „RB“VL  je možno podat před podpisem Zápisu o&nbsp;utkání kapitánem družstva. Tento protest je nutno zaznamenat do Zápisu o&nbsp;utkání písemně a&nbsp;to za přítomnosti rozhodčího. Stvrzením Zápisu o&nbsp;utkání bez podaného protestu se výsledek stává platným a&nbsp;nelze se proti němu odvolat.
</p>
<p>
  Veškeré spory řeší řídící rada „RB“VL.
Rozhodnutí rady je konečné a&nbsp;nelze se proti němu odvolat.
</p>


<h3>5. Závěrečné ustanovení</h3>


<h4>5.1    Vedení soutěže</h4>


<p>
  „RB“VL  je řízená radou. Vedení soutěže si vyhrazuje právo na změnu pravidel tak, aby byl zabezpečen hladký a&nbsp;bezproblémový průběh „RB“VL.
</p>
<p>
  Případné změny musí být zaslány či předány kontaktním osobám nejpozději před zahájením hracího dne od něhož změny platí.
</p>
<p>
  Řídící rada rozhoduje o&nbsp;všech záležitostech neuvedených v&nbsp;těchto PRAVIDLECH, jakož i&nbsp;o dalších problémech vzniklých v&nbsp;jednotlivých hracích dnech.
</p>


<h4>5.2     Platnost pravidel</h4>
<p>
  Tato pravidla jsou platná od 1.6.2013
</p>


<br /><br />
<p>
  Ve Frýdku Místku dne 15. května  2013
</p>
