<p>
  <strong>pro přihlášení družstva do 7. ročníku „Region Beskydy“ volejbalové ligy</strong>
</p>

<h2>Co je „RB“VL</h2>
<p>
  „Region Beskydy“ volejbalová liga („RB“VL) je dlouhodobá soutěž pro předem přihlášená volejbalová družstva, která budou bojovat o&nbsp;putovní pohár „RB“VL. 
</p>

<h2>Pro koho je „RB“VL určena</h2>
<p>
  Soutěž je určena pro neregistrované hráče. To je pro ty, kteří v&nbsp;aktuálním soutěžním ročníku nejsou na soupisce družstva hrající krajské a&nbsp;vyšší soutěže dospělých, ligové soutěže juniorů a&nbsp;kadetů organizované ČVS. Registrování hráči družstev okresních a&nbsp;městských soutěží jsou pro „RB“VL považování za neregistrované.
</p>

<h2>Kdy se bude „RB“VL hrát</h2>
<p>
  Začátkem soutěže bude druhá polovina října 2015. Půjde o&nbsp;6 (případně o&nbsp;7) hracích dnů a&nbsp;to jednou za měsíc od října 2015 do března (případně do dubna) 2016 (vždy v&nbsp;neděli), na kterých družstvo odehraje pokaždé tři až čtyři utkání.
</p>

<h2>Kde a&nbsp;jak se bude „RB“VL hrát</h2>
<p>
  Sedmý ročník „RB“VL se bude hrát opět ve sportovní hale u&nbsp;6. ZŠ v&nbsp;Místku, ul. Pionýrů na třech kurtech. Družstva budou startovat v&nbsp;Lize „A“ a&nbsp;v Lize „B“.
</p>

<h2>Kolik Vás bude „RB“VL stát</h2>
<p>
  Startovné činí 4&nbsp;200&nbsp;Kč na družstvo a&nbsp;soutěžní ročník. Bude z&nbsp;něj hrazeno nájemné haly, odměny rozhodčím, ceny vítězům, režijní náklady soutěže.
</p>

<h2>Jak se přihlásit do „RB“VL </h2>
<p>
  Přihlášku a soupisku najdete v&nbsp;sekci <a href="{plink Download:}">Ke stažení</a>.
</p>
<p>
  Řádně vyplněnou přihlášku a úhradu startovného je nutno provést nejpozději do 18.9.2015. Přihlášku odešlete do uvedeného termínu emailem na adresu: <a href="mailto:zdenek.licka@c-mail.cz">zdenek.licka@c-mail.cz</a> (kopii na adresu: <a href="mailto:werner.cigan@email.cz">werner.cigan@email.cz</a>). Případně ji doneste osobně na firmu SPORT SERVIS v&nbsp;sokolovně Frýdek-Místek, ul. Novodvorská 667 (nejlépe úterý a čtvrtek 9:00&nbsp;-&nbsp;12:00 a 13:00&nbsp;-&nbsp;17:00).
</p>
<p>
  Soupisky nutno dodat nejpozději do 2.10.2015 z důvodu kontroly registrovanosti.
</p>


<h2>Jak zaplatit startovné</h2>
<ul>
<li>příkazem k&nbsp;úhradě na níže uvedený účet vč. variabilního symbolu a&nbsp;zprávy pro příjemce (viz níže)</li>
<li>přímým bankovnictvím na níže uvedený účet vč. variabilního symbolu a&nbsp;zprávy pro příjemce (viz níže)</li>
<li>v hotovosti oproti potvrzení ve firmě SPORT SERVIS - Zdeněk Lička, Novodvorská 667 (sokolovna), 738 01 Frýdek-Místek a&nbsp;to nejlépe v&nbsp;úterý nebo ve čtvrtek od 9 do 17 hod.</li>
<li>družstva, která požadují vystavení faktury pro zaplacení startovného, musí o&nbsp;ni požádat v&nbsp;předstihu se sdělením přesného názvu subjektu, na který se má faktura vystavit</li>
</ul>

<h3>Bankovní spojení:</h3>
<dl>
<dt>banka:</dt>  <dd>FIO BANKA a.s.</dd>
<dt>číslo účtu:</dt>         <dd>2600551606/2010</dd>
<dt>variabilní symbol:</dt>  <dd>uveďte telefonní číslo vedoucího příslušného družstva</dd>
<dt>zpráva pro příjemce:</dt>  <dd>celý název družstva</dd>
</dl>
