<div class="panel-box">
  <div class="row">
    <div class="col-md-12">

<h3>Co je „RB“VL</h3>
<p>
  „Region Beskydy“ volejbalová liga („RB“VL) je dlouhodobá soutěž pro předem přihlášená volejbalová družstva, která budou bojovat o&nbsp;putovní pohár „RB“VL.
</p>

<h3>Pro koho je „RB“VL určena</h3>
<p>
  Soutěž je určena pro neregistrované hráče. To je pro ty, kteří v&nbsp;aktuálním soutěžním ročníku nejsou na soupisce družstva hrající krajské a&nbsp;vyšší soutěže dospělých, ligové soutěže juniorů a&nbsp;kadetů organizované ČVS. Registrování hráči družstev okresních a&nbsp;městských soutěží jsou pro „RB“VL považování za neregistrované.
</p>

<h3>Kdy se bude „RB“VL hrát</h3>
<p>
  Začátkem soutěže bude druhá polovina října 2017. Půjde o&nbsp;6 (případně o&nbsp;7) hracích dnů a&nbsp;to jednou za měsíc od října 2017 do března (případně do dubna) 2018 (vždy v&nbsp;neděli), na kterých družstvo odehraje pokaždé tři až čtyři utkání.
</p>

<h3>Kde a&nbsp;jak se bude „RB“VL hrát</h3>
<p>
  Tento ročník „RB“VL se bude hrát opět ve sportovní hale u&nbsp;6. ZŠ v&nbsp;Místku, ul. Pionýrů na třech kurtech. Družstva budou startovat v&nbsp;Lize „A“ a&nbsp;v Lize „B“.
</p>

<h3>Kolik Vás bude „RB“VL stát</h3>
<p>
  Startovné činí 4&nbsp;200&nbsp;Kč na družstvo a&nbsp;soutěžní ročník. Bude z&nbsp;něj hrazeno nájemné haly, odměny rozhodčím, ceny vítězům, režijní náklady soutěže.
</p>

<h3>Jak se přihlásit do „RB“VL </h3>
<p>
  Přihlášku a soupisku najdete v&nbsp;sekci <a href="{plink Download:}">Ke stažení</a>.
</p>
<p>
  Řádně vyplněnou přihlášku, soupisku s&nbsp;uvedením minimálně 8 hráčů a&nbsp;hráček (5 můžu a&nbsp;3 ženy) a úhradu startovného převodem na účet je nutno provést nejpozději do 15. 9. 2017. Přihlášku odešlete do uvedeného termínu emailem na adresu: <a href="mailto:werner.cigan@email.cz">werner.cigan@email.cz</a>.
</p>

<h3>Jak zaplatit startovné</h3>
<ul>
<li>příkazem k&nbsp;úhradě na níže uvedený účet vč. variabilního symbolu a&nbsp;zprávy pro příjemce (viz níže)</li>
<li>přímým bankovnictvím na níže uvedený účet vč. variabilního symbolu a&nbsp;zprávy pro příjemce (viz níže)</li>
<li>v hotovosti oproti potvrzení ve firmě SPORT SERVIS - Zdeněk Lička, Novodvorská 667 (sokolovna), 738 01 Frýdek-Místek a&nbsp;to nejlépe v&nbsp;úterý nebo ve čtvrtek od 9 do 17 hod.</li>
<li>družstva, která požadují vystavení faktury pro zaplacení startovného, musí o&nbsp;ni požádat v&nbsp;předstihu s&nbsp;písemným sdělením přesného názvu subjektu, na který se má faktura vystavit</li>
</ul>

<h3>Bankovní spojení:</h3>
<dl>
<dt>banka:</dt>  <dd>FIO BANKA a.s.</dd>
<dt>číslo účtu:</dt>         <dd>2600551606/2010</dd>
<dt>variabilní symbol:</dt>  <dd>uveďte telefonní číslo vedoucího příslušného družstva</dd>
<dt>zpráva pro příjemce:</dt>  <dd>celý název družstva</dd>
</dl>

<h3>Termín a podmínky přihlášení</h3>
<p>Platba a přihlášky včetně soupisek musí proběhnout do 15. 9. 2017.</p>
<p>Za termín přihlášení se bere datum připsání platby na účet (platí pro všechna družstva včetně zahraničních).</p>
<p>V případě nedodržení termínu platby bude u družstev Ligy&nbsp;„A“ nabídnuto místo družstvu z Ligy&nbsp;„B“. V případě družstev z Ligy „B“ nebude na samotnou přihlášku bez platby a&nbsp;soupisky brán zřetel.</p>

    </div>
  </div>
</div>
