<p>
  <strong>pro přihlášení družstva do 5. ročníku „Region Beskydy“ volejbalové ligy</strong>
</p>

<h3>Co je „RB“VL</h3>
<p>
  „Region Beskydy“ volejbalová liga („RB“VL) je dlouhodobá soutěž pro předem přihlášená volejbalová družstva, která budou bojovat o&nbsp;putovní pohár „RB“VL. 
</p>

<h3>Pro koho je „RB“VL určena</h3>
<p>
  Soutěž je určena pro neregistrované hráče. To je pro ty, kteří v&nbsp;aktuálním soutěžním ročníku nejsou na soupisce družstva hrající krajské a&nbsp;vyšší soutěže dospělých, ligové soutěže juniorů a&nbsp;kadetů organizované ČVS. Registrování hráči družstev okresních a&nbsp;městských soutěží jsou pro „RB“VL považování za neregistrované.
</p>

<h3>Kdy se bude „RB“VL hrát</h3>
<p>
  Začátkem soutěže bude druhá polovina října 2013. Půjde o&nbsp;6 (případně o&nbsp;7) hracích dnů a&nbsp;to jednou za měsíc od října 2013 do března (případně do dubna) 2014 (vždy v&nbsp;neděli), na kterých družstvo odehraje pokaždé tři až čtyři utkání.
</p>

<h3>Kde a&nbsp;jak se bude „RB“VL hrát</h3>
<p>
  Pátý ročník „RB“VL se bude hrát opět ve sportovní hale u&nbsp;6. ZŠ v&nbsp;Místku, ul. Pionýrů na třech kurtech. Družstva budou startovat v&nbsp;Lize „A“ a&nbsp;v Lize „B“.
</p>

<h3>Kolik Vás bude „RB“VL stát</h3>
<p>
  Startovné činí 4.000,- Kč na družstvo a&nbsp;soutěžní ročník. Bude z&nbsp;něj hrazeno nájemné haly, odměny rozhodčím, ceny vítězům, režijní náklady soutěže.
</p>

<h3>Jak se přihlásit do „RB“VL </h3>
<p>
  Přihlášku najdete v&nbsp;sekci <a href="{plink Download:}">Ke stažení</a>.
</p>
<p>
  Je nutné vyplnit přihlášku a&nbsp;zaplatit startovné nejpozději do 13.9.2013. Přihlášku odešlete do tohoto termínu na adresu:<br />
Zdeněk LIČKA, Padlých hrdinů 1425, 739 11 Frýdlant n. Ostr.<br />
nebo e-mailem na adresu: <a href="mailto:zdenek.licka@c-mail.cz">zdenek.licka@c-mail.cz</a>,<br>
případně osobně na firmě SPORT SERVIS v&nbsp;sokolovně Frýdek-Místek, ul. Novodvorská 667.
</p>


<h3>Jak zaplatit startovné</h3>
<ul>
<li>příkazem k&nbsp;úhradě na níže uvedený účet vč. variabilního symbolu a&nbsp;zprávy pro příjemce</li>
<li>přímým bankovnictvím na níže uvedený účet vč. variabilního symbolu a&nbsp;zprávy pro příjemce</li>
<li>v hotovosti ve firmě SPORT SERVIS - Zdeněk Lička, Novodvorská 667 (sokolovna), 738 01 Frýdek-Místek a&nbsp;to nejlépe v&nbsp;úterý nebo ve čtvrtek od 9 do 17 hod.</li>
<li>družstva, která požadují vystavení faktury pro zaplacení startovného, musí o&nbsp;ni požádat v&nbsp;předstihu se sdělením přesného názvu subjektu, na který se má faktura vystavit</li>
</ul>

<h3>Bankovní spojení:</h3>
<dl class="dl-horizontal">
<dt>banka:</dt>  <dd>FIO BANKA a.s.</dd>
<dt>číslo účtu:</dt>         <dd>2100405354/2010</dd>
<dt>variabilní symbol:</dt>  <dd>5</dd>
<dt>zpráva pro příjemce:</dt>  <dd>název družstva</dd>
</dl>
