<!--
<h4>Liga A - playoff</h4>
<ul>
  <li>Hrací den č. 6 - 25. 3. 2018</li>
  <ul>
   <li><a href="/download/rozlosovani-playoff-2018-a.pdf">pořadí zápasů</a></li>
   <li><a href="/download/playoff-2018-a.pdf">pavouk playoff</a></li>
  </ul>
</ul>

<h4>Liga B - playoff</h4>
<ul>
  <li>Hrací den č. 6 - 4. 3. 2018</li>
  <ul>
   <li><a href="/download/rozlosovani-playoff-2018-b.pdf">pořadí zápasů</a></li>
   <li><a href="/download/playoff-2018-b.pdf">pavouk playoff</a></li>
  </ul>
</ul>
-->

{foreach $terminy as $termin}
  {if $rocnikPopis != $termin->rocnik}
    {if $rocnikPopis !=  ""}
      </ul>
    {/if}
    <h4>{$termin->rocnik}</h4>
    <ul>
  {/if}
  <li><a href="{plink Rozlosovani:default, $termin->id}" title="Zobrazit rozlosování zápasů dne {$termin->datum|czechDate}">{$termin->termin}</a> - {$termin->datum|czechDate}</li>
  {assign $rocnikPopis $termin->rocnik}
  {if $iterator->isLast()}</ul>{/if}
{/foreach}
