<h4>Liga A - playoff</h4>
<ul>
  <li>Hrací den č. 6 - 19.3.2017</li>
<!--
  <ul>
   <li><a href="/download/rozlosovani_ligaa_playoff2016.pdf">pořadí zápasů</a></li>
   <li><a href="/download/ligaa_playoff_2016_vysl.pdf">pavouk playoff</a></li>
  </ul>
-->
</ul>

<h4>Liga B - playoff</h4>
<ul>
  <li>Hrací den č. 6 - 12.3.2017</li>
<!--
  <ul>
   <li><a href="/download/rozlosovani_ligab_playoff2016.pdf">pořadí zápasů</a></li>
   <li><a href="/download/ligab_playoff_2016_vysl.pdf">pavouk playoff</a></li>
  </ul>
-->
</ul>

{foreach $terminy as $termin}
  {if $rocnikPopis != $termin->rocnik}
    {if $rocnikPopis !=  ""}
      </ul>
    {/if}
    <h4>{$termin->rocnik}</h4>
    <ul>
  {/if}
  <li><a href="{plink Rozlosovani:default, $termin->id}" title="Zobrazit rozlosování zápasů dne {$termin->datum|czechDate}">{$termin->termin}</a> - {$termin->datum|czechDate}</li>
  {assign $rocnikPopis $termin->rocnik}
  {if $iterator->isLast()}</ul>{/if}
{/foreach}
