<div class="row">
  <div class="col-md-3 sidebar">
    <div class="panel-box">
      <div class="titles">
        <h4>Hrací dny</h4>
      </div>
      <div class="row">
        <div class="col-md-12">
  <h4>Liga A - playoff</h4>
  <ul>
    <li>Hrací den č. 6 - 22.3.2015</li>

    <ul>
     <li><a href="/download/rozlosovani_playoff2015_2.pdf">pořadí zápasů</a></li>
     <li><a href="/download/playoff_2015_vysl.pdf">pavouk playoff</a></li>
    </ul>
  </ul>

  {foreach $terminy as $termin}
    {if $rocnikPopis != $termin->rocnik}
      {if $rocnikPopis !=  ""}
        </ul>
      {/if}
      <h4>{$termin->rocnik}</h4>
      <ul>
    {/if}
    <li><a href="{plink Rozlosovani:default, $termin->id}" title="Zobrazit rozlosování zápasů dne {$termin->datum|czechDate}">{$termin->termin}</a> - {$termin->datum|czechDate}</li>
    {assign $rocnikPopis $termin->rocnik}
    {if $iterator->isLast()}</ul>{/if}
  {/foreach}


        </div> <!-- .col-md-12 -->
      </div> <!-- .row -->
    </div> <!-- .panel-box -->
  </div> <!-- .col-md-3 -->
  <div class="col-md-9">
{if count($rozlosovani)}
    <div class="panel-box">
      <div class="titles">
        <h4>Rozlosování hracího dne</h4>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="well text-center">
            <select id="druzstva" class="noPrint" onchange="zvyrazneniTymu()">
              <option value=" "> - - zvýraznit družstvo - - </option>
              {foreach $druzstva as $druzstvo}
              <option value="{$druzstvo->nazev}">{$druzstvo->nazev}</option>
              {/foreach}
            </select>
          </div>

  {foreach $rozlosovani as $zapas}
    {if $terminPopis != $zapas->termin}
      {if $terminPopis !=  ""}
        </table>
      {/if}
      {assign $barva 1}
              <h2>{$zapas->datum|czechDate} - {$zapas->termin}</h2>
              <h3>{$zapas->rocnik}</h3>

      <table class="table table-hover table-condensed">
        <thead>
        <tr>
          <th>začátek</th>
          <th>domácí</th>
          <th>&nbsp;</th>
          <th>hosté</th>
          <th>poznámka</th>
        </tr>
        </thead>
        <tbody>
    {/if}
    {if $cas != $zapas->cas}
      {assign $barva !$barva}
    {/if}
        <tr{if $barva} class="info"{/if}>
          <td>{$zapas->cas|czechTime}</td>
          <td>{if $zapas->domaci!=''}{$zapas->domaci}{else}{$zapas->skupina_popis}{$zapas->cislo_domaci}{/if}</td>
          <td>-</td>
          <td>{if $zapas->hoste!=''}{$zapas->hoste}{else}{$zapas->skupina_popis}{$zapas->cislo_hoste}{/if}</td>
          <td>{!$zapas->poznamka}</td>
        </tr>
    {assign $terminPopis $zapas->termin}
    {assign $cas $zapas->cas}
    {if $iterator->isLast()}</tbody></table>{/if}
  {/foreach}

        </div> <!-- .col-md-12 -->
      </div> <!-- .row -->
    </div> <!-- .panel-box -->
{/if}
  </div> <!-- .col-md-9 -->
</div> <!-- .row -->
