<div class="panel-box">
  <div class="row">
    <div class="col-md-12">
<p>
  <a class="btn btn-primary" href="{link add}" title="Přidat nového uživatele"><span class="glyphicon glyphicon-plus"></span> Nový uživatel</a>
</p>

<table class="table table-striped table-hover table-condensed">
  <thead>
    <tr>
      <th>id</th>
      <th>jméno</th>
      <th>oprávnění</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
{foreach $rows as $row}
<tr{if $iterator->isEven()} class="even"{/if}>
    <td>{$row->id}</td>
    <td>{$row->username}</td>
    <td>{=$row->role == 'admin' ? 'Administrátor' : 'Uživatel'}</td>
    <td>
      <div class="btn-group pull-right">
        <a class="btn btn-default btn-xs" href="{link edit, $row->id}" title="upravit uživatele {$row->username}"><span class="glyphicon glyphicon-pencil"></span></a>
        <a class="btn btn-default btn-xs" href="{link delete, $row->id}" title="smazat uživatele {$row->username}"><span class="glyphicon glyphicon-remove"></span></a>
      </div>
    </td>
</tr>
{/foreach}
  </tbody>
</table>
    </div>
  </div>
</div>
