<p>
  <a class="btn btn-success" href="{link add}" title="Přidat nového uživatele"><i class="icon-plus icon-white"></i> Nový uživatel</a>
</p>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>id</th>
      <th>jméno</th>
      <th>oprávnění</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
{foreach $rows as $row}
<tr{if $iterator->isEven()} class="even"{/if}>
    <td>{$row->id}</td>
    <td>{$row->username}</td>
    <td>{=$row->role == 'admin' ? 'Administrátor' : 'Uživatel'}</td>
    <td>
      <div class="btn-group pull-right">
        <a class="btn btn-mini" href="{link edit, $row->id}" title="upravit uživatele {$row->username}"><i class="icon-pencil"></i></a>
        <a class="btn btn-mini" href="{link delete, $row->id}" title="smazat uživatele {$row->username}"><i class="icon-remove"></i></a>
      </div>
    </td>
</tr>
{/foreach}
  </tbody>
</table>
