
<h3>Liga A - play off</h3>
<ul>
 <li><a href="http://www.rbvl.cz/download/playoff_2013.pdf">Hrací den č. 6</a> - 24.3.2013</li>
</ul>



{foreach $terminy as $termin}
  {if $rocnikPopis != $termin->rocnik}
    {if $rocnikPopis !=  ""}
      </ul>
    {/if}
    <h3>{$termin->rocnik}</h3>
    <ul>
      <li><a href="{plink Vysledky:tabulky, $termin->id_rocnik}" title="Zobrazit celkové tabulky soutěže {$termin->rocnik}">Celkové tabulky</a></li>
  {/if}
  <li><a href="{plink Vysledky:termin, $termin->id}" title="Zobrazit výsledky zápasů ze dne {$termin->datum|czechDate}">{$termin->termin}</a> - {$termin->datum|czechDate}</li>
  {assign $rocnikPopis $termin->rocnik}
  {if $iterator->isLast()}</ul>{/if}
{/foreach}



