<select id="druzstva" onchange="zvyrazneniTymu()" class="noPrint">
  <option value=""> - - zvýraznit družstvo - - </option>
  {foreach $druzstva as $druzstvo}
  <option value="{$druzstvo->nazev}">{$druzstvo->nazev}</option>
  {/foreach}
</select>

{foreach $zapasy as $zapas}
  {if $datum != $zapas->datum && $skupina != $zapas->skupina}
    {if $datum != ""}
      </tbody></table>
    {/if}
    <h3>{$zapas->datum|czechDate} - {$zapas->termin}</h3>
    <h4>{$zapas->skupina}</h4>
    <table class="vysledky table table-striped table-hover table-condensed">
      <thead>
        <tr>
          <th class="span3">domácí</th>
          <th class="span3">hosté</th>
          <th class="span3">výsledek</th>
          <!-- <th>poznámka</th> -->
        </tr>
      </thead>
      <tbody>
  {elseif $skupina != $zapas->skupina}
    {if $skupina != ""}
      </tbody></table>
    {/if}
    <h4>{$zapas->skupina}</h4>
    <table class="vysledky table table-striped table-hover table-condensed">
      <thead>
        <tr>
          <th class="span3">domácí</th>
          <th class="span3">hosté</th>
          <th class="span3">výsledek</th>
          <!-- <th>poznámka</th> -->
        </tr>
      </thead>
      <tbody>
  {/if}
  <tr{if $iterator->isEven()} class="even"{/if}>
      <td>{$zapas->domaci_nazev}</td>
      <td>{$zapas->hoste_nazev}</td>
      <td>
        {if $zapas->sety_domaci == 0 && $zapas->sety_hoste == 0}
        &nbsp;
        {else}
          {if $zapas->kontumace_domaci}X{else}{$zapas->sety_domaci}{/if}:{if $zapas->kontumace_hoste}X{else}{$zapas->sety_hoste}{/if}
          ({$zapas->mice1_domaci}:{$zapas->mice1_hoste}, {$zapas->mice2_domaci}:{$zapas->mice2_hoste}{if $zapas->mice3_domaci != 0 && $zapas->mice3_hoste != 0}, {$zapas->mice3_domaci}:{$zapas->mice3_hoste}{/if})
        {/if}
        {if isset($user)}
          <div class="pull-right">
            <a class="btn btn-default btn-xs" href="{plink edit, $zapas->id}" title="upravit výsledek"><span class="glyphicon glyphicon-pencil"></span></a>
          </div>
        {/if}
      </td>
      <!-- <td>{$zapas->poznamka}</td> -->
  </tr>
  {assign $datum $zapas->datum}
  {assign $skupina $zapas->skupina}
{/foreach}
</tbody></table>