<div class="row">
  <div class="col-md-3 sidebar">
    <div class="panel-box">
      <div class="titles">
        <h4>Hrací dny</h4>
      </div>
      <div class="row">
        <div class="col-md-12">
          <h4>Liga A - play off</h4>
          <ul>
            <li><a href="http://www.rbvl.cz/download/playoff_2015_vysl.pdf">Hrací den č. 6</a> - 22.3.2015</li>
          </ul>

          {foreach $terminy as $termin}
            {if $rocnikPopis != $termin->rocnik}
              {if $rocnikPopis !=  ""}
                </ul>
              {/if}
              <h4>{$termin->rocnik}</h4>
              <ul>
                <li><a href="{plink Vysledky:tabulky, $termin->id_rocnik}" title="Zobrazit celkové tabulky soutěže {$termin->rocnik}">Celkové tabulky</a></li>
            {/if}
            <li><a href="{plink Vysledky:termin, $termin->id}" title="Zobrazit výsledky zápasů ze dne {$termin->datum|czechDate}">{$termin->termin}</a> - {$termin->datum|czechDate}</li>
            {assign $rocnikPopis $termin->rocnik}
            {if $iterator->isLast()}</ul>{/if}
          {/foreach}
        </div> <!-- .col-md-12 -->
      </div> <!-- .row -->
    </div> <!-- .panel-box -->
  </div> <!-- .col-md-3 -->
  <div class="col-md-9">
    <div class="panel-box">
      <div class="titles">
        <h4>Celkové tabulky</h4>
      </div>
      <div class="row">
        <div class="col-md-12">
<ul>
<li><strong>c</strong> - počet zápasů</li>
<li><strong>v</strong> - výhry 2:0 (3 body)</li>
<li><strong>vt</strong> - výhry 2:1 (2 body)</li>
<li><strong>pt</strong> - prohry 1:2 (1 bod)</li>
<li><strong>p</strong> - prohry 0:2 (0 bodů)</li>
<li><strong>pk</strong> - kontumace (-1 bod)</li>
</ul>

{foreach $tabulky as $row}
  {if $skupina != $row->skupina_popis}
    {if $skupina !=  ""}
      </table>
    {/if}
    <h3>{$row->skupina_popis}</h3>
    {assign $poradi 1}
    <table class="tabulky table table-striped  table-hover table-condensed">
    <thead>
    <tr><th>pořadí</th><th class="druzstvo">družstvo</th><th>c</th><th>v</th><th>vt</th><th>pt</th><th>p</th><th>pk</th><th colspan="2">sety</th><th colspan="2">míče</th><th>body</th></tr>
    </thead>
    <tbody>
  {/if}
  <tr{if $iterator->isEven()} class="even"{/if}><td>{$poradi}.</td><td>{$row->druzstvo_nazev}</td><td>{$row->c}</td><td>{$row->v}</td><td>{$row->vt}</td><td>{$row->pt}</td><td>{$row->p}</td><td>{$row->pk}</td><td>{$row->sety_dal}:{$row->sety_dostal}</td><td>({$row->sety|round3})</td><td>{$row->mice_dal}:{$row->mice_dostal}</td><td>({$row->mice|round3})</td><td>{$row->body}</td></tr>
  {assign $skupina $row->skupina_popis}
  <?php $poradi++?>
  {if $iterator->isLast()}</tbody></table>{/if}
{/foreach}
        </div> <!-- .col-md-12 -->
      </div> <!-- .row -->
    </div> <!-- .panel-box -->
  </div> <!-- .col-md-9 -->
</div> <!-- .row -->
