<div class="row">
  <div class="col-md-3 sidebar">
    <div class="panel-box">
      <div class="titles">
        <h4>Hrací dny</h4>
      </div>
      <div class="row">
        <div class="col-md-12">
          <h4>Liga A - play off</h4>
          <ul>
            <li><a href="http://www.rbvl.cz/download/playoff_2015_vysl.pdf">Hrací den č. 6</a> - 22.3.2015</li>
          </ul>

          {foreach $terminy as $termin}
            {if $rocnikPopis != $termin->rocnik}
              {if $rocnikPopis !=  ""}
                </ul>
              {/if}
              <h4>{$termin->rocnik}</h4>
              <ul>
                <li><a href="{plink Vysledky:tabulky, $termin->id_rocnik}" title="Zobrazit celkové tabulky soutěže {$termin->rocnik}">Celkové tabulky</a></li>
            {/if}
            <li><a href="{plink Vysledky:termin, $termin->id}" title="Zobrazit výsledky zápasů ze dne {$termin->datum|czechDate}">{$termin->termin}</a> - {$termin->datum|czechDate}</li>
            {assign $rocnikPopis $termin->rocnik}
            {if $iterator->isLast()}</ul>{/if}
          {/foreach}
        </div> <!-- .col-md-12 -->
      </div> <!-- .row -->
    </div> <!-- .panel-box -->
  </div> <!-- .col-md-3 -->
  <div class="col-md-9">
  </div> <!-- .col-md-9 -->
</div> <!-- .row -->