<div class="row">
  <div class="col-md-3 sidebar">
    <div class="panel-box">
      <div class="titles">
        <h4>Hrací dny</h4>
      </div>
      <div class="row">
        <div class="col-md-12">
          <h4>Liga A - play off</h4>
          <ul>
            <li><a href="http://www.rbvl.cz/download/playoff_2015_vysl.pdf">Hrací den č. 6</a> - 22.3.2015</li>
          </ul>

          {foreach $terminy as $termin}
            {if $rocnikPopis != $termin->rocnik}
              {if $rocnikPopis !=  ""}
                </ul>
              {/if}
              <h4>{$termin->rocnik}</h4>
              <ul>
                <li><a href="{plink Vysledky:tabulky, $termin->id_rocnik}" title="Zobrazit celkové tabulky soutěže {$termin->rocnik}">Celkové tabulky</a></li>
            {/if}
            <li><a href="{plink Vysledky:termin, $termin->id}" title="Zobrazit výsledky zápasů ze dne {$termin->datum|czechDate}">{$termin->termin}</a> - {$termin->datum|czechDate}</li>
            {assign $rocnikPopis $termin->rocnik}
            {if $iterator->isLast()}</ul>{/if}
          {/foreach}
        </div> <!-- .col-md-12 -->
      </div> <!-- .row -->
    </div> <!-- .panel-box -->
  </div> <!-- .col-md-3 -->
  <div class="col-md-9">
    <div class="panel-box">
      <div class="titles">
        <h4>Výsledky hracího dne</h4>
      </div>
      <div class="row">
        <div class="col-md-12">
          <div class="well text-center">
            <select id="druzstva" onchange="zvyrazneniTymu()" class="noPrint">
              <option value=""> - - zvýraznit družstvo - - </option>
              {foreach $druzstva as $druzstvo}
              <option value="{$druzstvo->nazev}">{$druzstvo->nazev}</option>
              {/foreach}
            </select>
          </div>

          {foreach $zapasy as $zapas}
            {if $datum != $zapas->datum && $skupina != $zapas->skupina}
              {if $datum != ""}
                </tbody></table>
              {/if}
              <h2>{$zapas->datum|czechDate} - {$zapas->termin}</h2>
              <h3>{$zapas->skupina}</h3>
              <table class="vysledky table table-striped table-hover table-condensed">
                <thead>
                  <tr>
                    <th class="span3">domácí</th>
                    <th class="span3">hosté</th>
                    <th class="span3">výsledek</th>
                  </tr>
                </thead>
                <tbody>
            {elseif $skupina != $zapas->skupina}
              {if $skupina != ""}
                </tbody></table>
              {/if}
              <h4>{$zapas->skupina}</h4>
              <table class="vysledky table table-striped table-hover table-condensed">
                <thead>
                  <tr>
                    <th class="span3">domácí</th>
                    <th class="span3">hosté</th>
                    <th class="span3">výsledek</th>
                  </tr>
                </thead>
                <tbody>
            {/if}
            <tr>
                <td>{$zapas->domaci_nazev}</td>
                <td>{$zapas->hoste_nazev}</td>
                <td>
                  {if $zapas->sety_domaci == 0 && $zapas->sety_hoste == 0}
                  &nbsp;
                  {else}
                    {if $zapas->kontumace_domaci}X{else}{$zapas->sety_domaci}{/if}:{if $zapas->kontumace_hoste}X{else}{$zapas->sety_hoste}{/if}
                    ({$zapas->mice1_domaci}:{$zapas->mice1_hoste}, {$zapas->mice2_domaci}:{$zapas->mice2_hoste}{if $zapas->mice3_domaci != 0 && $zapas->mice3_hoste != 0}, {$zapas->mice3_domaci}:{$zapas->mice3_hoste}{/if})
                  {/if}
                  {if isset($user)}
                    <div class="pull-right">
                      <a class="btn btn-default btn-xs" href="{plink edit, $zapas->id}" title="upravit výsledek"><span class="glyphicon glyphicon-pencil"></span></a>
                    </div>
                  {/if}
                </td>
            </tr>
            {assign $datum $zapas->datum}
            {assign $skupina $zapas->skupina}
          {/foreach}
          </tbody></table>
        </div> <!-- .col-md-12 -->
      </div> <!-- .row -->
    </div> <!-- .panel-box -->
  </div> <!-- .col-md-9 -->
</div> <!-- .row -->
