<div class="row">
  <div class="col-md-12">
    <div class="panel-box">
      <div class="row">
        <div class="col-md-12">
<p>
  {$vysledek->termin_popis} - <a href="{link Vysledky:termin, $vysledek->termin}">zpět na výsledky</a>
</p>

<h3>{$vysledek->domaci_nazev} - {$vysledek->hoste_nazev}</h3>

<p>
 <strong>{$vysledek->datum|czechDate} v {$vysledek->cas|czechTime}</strong>
</p>

{$form->render('begin')}
  <div class="form-group">
    {$form['sety_domaci']->getLabel()->class('col-sm-1')}
      {$form['sety_domaci']->control->class('form-control')}
      <span>:</span>
      {$form['sety_hoste']->control->class('form-control')}

  </div>

  <div class="form-group">
    {$form['mice1_domaci']->getLabel()->class('col-sm-1')}
    {$form['mice1_domaci']->control->class('form-control')}
    <span>:</span>
    {$form['mice1_hoste']->control->class('form-control')}
    <span> , </span>
    {$form['mice2_domaci']->control->class('form-control')}
    <span>:</span>
    {$form['mice2_hoste']->control->class('form-control')}
    <span> , </span>
    {$form['mice3_domaci']->control->class('form-control')}
    <span>:</span>
    {$form['mice3_hoste']->control->class('form-control')}
  </div>

  <div class="form-group">
    <div class="checkbox">
      <label>
        {$form['kontumace_domaci']->control}
        Kontumační prohra domácích
      </label>
    </div>
    <div class="checkbox">
      <label>
        {$form['kontumace_hoste']->control}
        Kontumační prohra hostů
      </label>
    </div>
  </div>

  <div class="form-group">
    {$form['saveAndNext']->control->class('btn btn-primary')}
    {$form['save']->control->class('btn btn-primary')}
  </div>
{$form->render('end')}
        </div> <!-- .col-md-12 -->
      </div> <!-- .row -->
    </div> <!-- .panel-box -->
  </div> <!-- .col-md-12 -->
</div> <!-- .row -->
